/** \file
 *  This C source file was generated by $ANTLR version 3.1.3 Mar 18, 2009 10:09:25
 *
 *     -  From the grammar source file : Interp.g
 *     -                            On : 2009-10-09 20:39:27
 *     -                for the parser : InterpParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

#include <vector>
#include<iostream>
#include "Element.h"
#include "VariableElement.h"
#include "MatrixVariableElement.h"
#include "MatrixValueElement.h"
#include "MatrixAssignmentOperationElement.h"
#include "MatrixPrintOperationElement.h"
#include "MatrixMultiplyOperationElement.h"
#include "MatrixAdditionOperationElement.h"
#include "IntegerElement.h"
#include "AssignmentOperationElement.h"
#include "AdditionOperationElement.h"
#include "PrintOperationElement.h"
#include "MultiplyOperationElement.h"

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "InterpParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pInterpParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pInterpParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pInterpParser_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   InterpParserTokenNames[12+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "ASSIGNMENT",
        (pANTLR3_UINT8) "END_OF_STATEMENT",
        (pANTLR3_UINT8) "MATRIXVARIABLE",
        (pANTLR3_UINT8) "MATRIXVALUE",
        (pANTLR3_UINT8) "VARIABLE",
        (pANTLR3_UINT8) "INT_LITERAL",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "PRODUCT",
        (pANTLR3_UINT8) "RSQBRACKET",
        (pANTLR3_UINT8) "LSQBRACKET",
        (pANTLR3_UINT8) "WHITESPACE",
        (pANTLR3_UINT8) "'print'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static InterpParser_program_return	program    (pInterpParser ctx);
static InterpParser_expr_return	expr    (pInterpParser ctx);
static InterpParser_matrixassignment_return	matrixassignment    (pInterpParser ctx);
static InterpParser_matrixaddition_return	matrixaddition    (pInterpParser ctx);
static InterpParser_matrixmultiply_return	matrixmultiply    (pInterpParser ctx);
static InterpParser_matrixvariable_return	matrixvariable    (pInterpParser ctx);
static InterpParser_matrixvalue_return	matrixvalue    (pInterpParser ctx);
static InterpParser_matrixprint_return	matrixprint    (pInterpParser ctx);
static InterpParser_assignment_return	assignment    (pInterpParser ctx);
static InterpParser_var_or_int_literal_return	var_or_int_literal    (pInterpParser ctx);
static InterpParser_variable_return	variable    (pInterpParser ctx);
static InterpParser_int_literal_return	int_literal    (pInterpParser ctx);
static InterpParser_addition_return	addition    (pInterpParser ctx);
static InterpParser_multiply_return	multiply    (pInterpParser ctx);
static InterpParser_print_return	print    (pInterpParser ctx);
static void	InterpParserFree(pInterpParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "Interp.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new InterpParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pInterpParser
InterpParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return InterpParserNewSSD(instream, NULL);
}

/** \brief Create a new InterpParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pInterpParser
InterpParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pInterpParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pInterpParser) ANTLR3_CALLOC(1, sizeof(InterpParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in InterpParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our InterpParser interface
     */
    ctx->program	= program;
    ctx->expr	= expr;
    ctx->matrixassignment	= matrixassignment;
    ctx->matrixaddition	= matrixaddition;
    ctx->matrixmultiply	= matrixmultiply;
    ctx->matrixvariable	= matrixvariable;
    ctx->matrixvalue	= matrixvalue;
    ctx->matrixprint	= matrixprint;
    ctx->assignment	= assignment;
    ctx->var_or_int_literal	= var_or_int_literal;
    ctx->variable	= variable;
    ctx->int_literal	= int_literal;
    ctx->addition	= addition;
    ctx->multiply	= multiply;
    ctx->print	= print;
    ctx->free			= InterpParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */
    ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);
    ctx->vectors	= antlr3VectorFactoryNew(0);
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = InterpParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 InterpParserFree(pInterpParser ctx)
 {
    /* Free any scope memory
     */
    
    ctx->vectors->close(ctx->vectors);
    /* We created the adaptor so we must free it
     */
    ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return InterpParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_program66  */
static	ANTLR3_BITWORD FOLLOW_expr_in_program66_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008142) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_program66	= { FOLLOW_expr_in_program66_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignment_in_expr100  */
static	ANTLR3_BITWORD FOLLOW_assignment_in_expr100_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_assignment_in_expr100	= { FOLLOW_assignment_in_expr100_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixassignment_in_expr108  */
static	ANTLR3_BITWORD FOLLOW_matrixassignment_in_expr108_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixassignment_in_expr108	= { FOLLOW_matrixassignment_in_expr108_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_print_in_expr116  */
static	ANTLR3_BITWORD FOLLOW_print_in_expr116_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_print_in_expr116	= { FOLLOW_print_in_expr116_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixprint_in_expr124  */
static	ANTLR3_BITWORD FOLLOW_matrixprint_in_expr124_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixprint_in_expr124	= { FOLLOW_matrixprint_in_expr124_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixassignment147  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixassignment147_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixassignment147	= { FOLLOW_matrixvariable_in_matrixassignment147_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGNMENT_in_matrixassignment155  */
static	ANTLR3_BITWORD FOLLOW_ASSIGNMENT_in_matrixassignment155_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000000C0) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGNMENT_in_matrixassignment155	= { FOLLOW_ASSIGNMENT_in_matrixassignment155_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvalue_in_matrixassignment160  */
static	ANTLR3_BITWORD FOLLOW_matrixvalue_in_matrixassignment160_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvalue_in_matrixassignment160	= { FOLLOW_matrixvalue_in_matrixassignment160_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixaddition_in_matrixassignment170  */
static	ANTLR3_BITWORD FOLLOW_matrixaddition_in_matrixassignment170_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixaddition_in_matrixassignment170	= { FOLLOW_matrixaddition_in_matrixassignment170_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixmultiply_in_matrixassignment177  */
static	ANTLR3_BITWORD FOLLOW_matrixmultiply_in_matrixassignment177_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixmultiply_in_matrixassignment177	= { FOLLOW_matrixmultiply_in_matrixassignment177_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_matrixassignment188  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_matrixassignment188_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_matrixassignment188	= { FOLLOW_END_OF_STATEMENT_in_matrixassignment188_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixaddition212  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixaddition212_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixaddition212	= { FOLLOW_matrixvariable_in_matrixaddition212_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_matrixaddition221  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_matrixaddition221_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_matrixaddition221	= { FOLLOW_PLUS_in_matrixaddition221_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixaddition230  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixaddition230_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixaddition230	= { FOLLOW_matrixvariable_in_matrixaddition230_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixmultiply252  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixmultiply252_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixmultiply252	= { FOLLOW_matrixvariable_in_matrixmultiply252_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRODUCT_in_matrixmultiply261  */
static	ANTLR3_BITWORD FOLLOW_PRODUCT_in_matrixmultiply261_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_PRODUCT_in_matrixmultiply261	= { FOLLOW_PRODUCT_in_matrixmultiply261_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixmultiply268  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixmultiply268_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixmultiply268	= { FOLLOW_matrixvariable_in_matrixmultiply268_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MATRIXVARIABLE_in_matrixvariable289  */
static	ANTLR3_BITWORD FOLLOW_MATRIXVARIABLE_in_matrixvariable289_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_MATRIXVARIABLE_in_matrixvariable289	= { FOLLOW_MATRIXVARIABLE_in_matrixvariable289_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MATRIXVALUE_in_matrixvalue312  */
static	ANTLR3_BITWORD FOLLOW_MATRIXVALUE_in_matrixvalue312_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_MATRIXVALUE_in_matrixvalue312	= { FOLLOW_MATRIXVALUE_in_matrixvalue312_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_matrixprint334  */
static	ANTLR3_BITWORD FOLLOW_15_in_matrixprint334_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_matrixprint334	= { FOLLOW_15_in_matrixprint334_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixprint336  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixprint336_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixprint336	= { FOLLOW_matrixvariable_in_matrixprint336_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_matrixprint344  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_matrixprint344_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_matrixprint344	= { FOLLOW_END_OF_STATEMENT_in_matrixprint344_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_variable_in_assignment365  */
static	ANTLR3_BITWORD FOLLOW_variable_in_assignment365_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_variable_in_assignment365	= { FOLLOW_variable_in_assignment365_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGNMENT_in_assignment373  */
static	ANTLR3_BITWORD FOLLOW_ASSIGNMENT_in_assignment373_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGNMENT_in_assignment373	= { FOLLOW_ASSIGNMENT_in_assignment373_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_assignment378  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_assignment378_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_assignment378	= { FOLLOW_var_or_int_literal_in_assignment378_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_addition_in_assignment390  */
static	ANTLR3_BITWORD FOLLOW_addition_in_assignment390_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_addition_in_assignment390	= { FOLLOW_addition_in_assignment390_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multiply_in_assignment396  */
static	ANTLR3_BITWORD FOLLOW_multiply_in_assignment396_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_multiply_in_assignment396	= { FOLLOW_multiply_in_assignment396_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_assignment406  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_assignment406_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_assignment406	= { FOLLOW_END_OF_STATEMENT_in_assignment406_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_variable_in_var_or_int_literal422  */
static	ANTLR3_BITWORD FOLLOW_variable_in_var_or_int_literal422_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_variable_in_var_or_int_literal422	= { FOLLOW_variable_in_var_or_int_literal422_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_int_literal_in_var_or_int_literal433  */
static	ANTLR3_BITWORD FOLLOW_int_literal_in_var_or_int_literal433_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_int_literal_in_var_or_int_literal433	= { FOLLOW_int_literal_in_var_or_int_literal433_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_VARIABLE_in_variable457  */
static	ANTLR3_BITWORD FOLLOW_VARIABLE_in_variable457_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_VARIABLE_in_variable457	= { FOLLOW_VARIABLE_in_variable457_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_LITERAL_in_int_literal487  */
static	ANTLR3_BITWORD FOLLOW_INT_LITERAL_in_int_literal487_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_LITERAL_in_int_literal487	= { FOLLOW_INT_LITERAL_in_int_literal487_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_addition524  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_addition524_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_addition524	= { FOLLOW_var_or_int_literal_in_addition524_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_addition533  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_addition533_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_addition533	= { FOLLOW_PLUS_in_addition533_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_addition542  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_addition542_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_addition542	= { FOLLOW_var_or_int_literal_in_addition542_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_multiply564  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_multiply564_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_multiply564	= { FOLLOW_var_or_int_literal_in_multiply564_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRODUCT_in_multiply573  */
static	ANTLR3_BITWORD FOLLOW_PRODUCT_in_multiply573_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_PRODUCT_in_multiply573	= { FOLLOW_PRODUCT_in_multiply573_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_multiply580  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_multiply580_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_multiply580	= { FOLLOW_var_or_int_literal_in_multiply580_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_print602  */
static	ANTLR3_BITWORD FOLLOW_15_in_print602_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_print602	= { FOLLOW_15_in_print602_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_print604  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_print604_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_print604	= { FOLLOW_var_or_int_literal_in_print604_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_print612  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_print612_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_print612	= { FOLLOW_END_OF_STATEMENT_in_print612_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start program
 * Interp.g:56:1: program returns [std::vector<Element *> * ret] : ( expr )+ ;
 */
static InterpParser_program_return
program(pInterpParser ctx)
{   
    InterpParser_program_return retval;

    pANTLR3_BASE_TREE root_0;

    InterpParser_expr_return expr1;
    #undef	RETURN_TYPE_expr1
    #define	RETURN_TYPE_expr1 InterpParser_expr_return


    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new std::vector<Element *>();

    expr1.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // Interp.g:60:3: ( ( expr )+ )
        // Interp.g:60:5: ( expr )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            // Interp.g:60:5: ( expr )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA1_0 = LA(1);
            	    if ( (LA1_0 == MATRIXVARIABLE || LA1_0 == VARIABLE || LA1_0 == 15) ) 
            	    {
            	        alt1=1;
            	    }

            	}
            	switch (alt1) 
            	{
            	    case 1:
            	        // Interp.g:60:6: expr
            	        {
            	            FOLLOWPUSH(FOLLOW_expr_in_program66);
            	            expr1=expr(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogramEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, expr1.tree);
            	            {
            	                ret->push_back(expr1.ret); 
            	            }

            	        }
            	        break;

            	    default:
            	    
            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogramEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleprogramEx; /* Prevent compiler warnings */
    ruleprogramEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end program */

/** 
 * $ANTLR start expr
 * Interp.g:64:1: expr returns [Element * ret] : ( assignment | matrixassignment | print | matrixprint );
 */
static InterpParser_expr_return
expr(pInterpParser ctx)
{   
    InterpParser_expr_return retval;

    pANTLR3_BASE_TREE root_0;

    InterpParser_assignment_return assignment2;
    #undef	RETURN_TYPE_assignment2
    #define	RETURN_TYPE_assignment2 InterpParser_assignment_return

    InterpParser_matrixassignment_return matrixassignment3;
    #undef	RETURN_TYPE_matrixassignment3
    #define	RETURN_TYPE_matrixassignment3 InterpParser_matrixassignment_return

    InterpParser_print_return print4;
    #undef	RETURN_TYPE_print4
    #define	RETURN_TYPE_print4 InterpParser_print_return

    InterpParser_matrixprint_return matrixprint5;
    #undef	RETURN_TYPE_matrixprint5
    #define	RETURN_TYPE_matrixprint5 InterpParser_matrixprint_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    assignment2.tree = NULL;

    matrixassignment3.tree = NULL;

    print4.tree = NULL;

    matrixprint5.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        {
            //  Interp.g:65:3: ( assignment | matrixassignment | print | matrixprint )
            
            ANTLR3_UINT32 alt2;

            alt2=4;

            switch ( LA(1) ) 
            {
            case VARIABLE:
            	{
            		alt2=1;
            	}
                break;
            case MATRIXVARIABLE:
            	{
            		alt2=2;
            	}
                break;
            case 15:
            	{

            		{
            		    int LA2_3 = LA(2);
            		    if ( (((LA2_3 >= VARIABLE) && (LA2_3 <= INT_LITERAL))) ) 
            		    {
            		        alt2=3;
            		    }
            		    else if ( (LA2_3 == MATRIXVARIABLE) ) 
            		    {
            		        alt2=4;
            		    }
            		    else 
            		    {
            		    
            		        CONSTRUCTEX();
            		        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		        EXCEPTION->message      = (void *)"";
            		        EXCEPTION->decisionNum  = 2;
            		        EXCEPTION->state        = 3;


            		        goto ruleexprEx;
            		    }
            		}
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto ruleexprEx;
            }

            switch (alt2) 
            {
        	case 1:
        	    // Interp.g:65:5: assignment
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_assignment_in_expr100);
        	        assignment2=assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, assignment2.tree);
        	        {
        	            ret = assignment2.ret;
        	        }

        	    }
        	    break;
        	case 2:
        	    // Interp.g:66:5: matrixassignment
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_matrixassignment_in_expr108);
        	        matrixassignment3=matrixassignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, matrixassignment3.tree);
        	        {
        	            ret=matrixassignment3.ret;
        	        }

        	    }
        	    break;
        	case 3:
        	    // Interp.g:67:5: print
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_print_in_expr116);
        	        print4=print(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, print4.tree);
        	        {
        	             ret = print4.ret; 
        	        }

        	    }
        	    break;
        	case 4:
        	    // Interp.g:68:5: matrixprint
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_matrixprint_in_expr124);
        	        matrixprint5=matrixprint(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, matrixprint5.tree);
        	        {
        	            ret = matrixprint5.ret; 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end expr */

/** 
 * $ANTLR start matrixassignment
 * Interp.g:70:1: matrixassignment returns [MatrixAssignmentOperationElement * ret] : matrixvariable ASSIGNMENT ( matrixvalue | matrixaddition | matrixmultiply ) END_OF_STATEMENT ;
 */
static InterpParser_matrixassignment_return
matrixassignment(pInterpParser ctx)
{   
    InterpParser_matrixassignment_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    ASSIGNMENT7;
    pANTLR3_COMMON_TOKEN    END_OF_STATEMENT11;
    InterpParser_matrixvariable_return matrixvariable6;
    #undef	RETURN_TYPE_matrixvariable6
    #define	RETURN_TYPE_matrixvariable6 InterpParser_matrixvariable_return

    InterpParser_matrixvalue_return matrixvalue8;
    #undef	RETURN_TYPE_matrixvalue8
    #define	RETURN_TYPE_matrixvalue8 InterpParser_matrixvalue_return

    InterpParser_matrixaddition_return matrixaddition9;
    #undef	RETURN_TYPE_matrixaddition9
    #define	RETURN_TYPE_matrixaddition9 InterpParser_matrixaddition_return

    InterpParser_matrixmultiply_return matrixmultiply10;
    #undef	RETURN_TYPE_matrixmultiply10
    #define	RETURN_TYPE_matrixmultiply10 InterpParser_matrixmultiply_return

    pANTLR3_BASE_TREE ASSIGNMENT7_tree;
    pANTLR3_BASE_TREE END_OF_STATEMENT11_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new MatrixAssignmentOperationElement();

    ASSIGNMENT7       = NULL;
    END_OF_STATEMENT11       = NULL;
    matrixvariable6.tree = NULL;

    matrixvalue8.tree = NULL;

    matrixaddition9.tree = NULL;

    matrixmultiply10.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    ASSIGNMENT7_tree   = NULL;
    END_OF_STATEMENT11_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:74:3: ( matrixvariable ASSIGNMENT ( matrixvalue | matrixaddition | matrixmultiply ) END_OF_STATEMENT )
        // Interp.g:74:5: matrixvariable ASSIGNMENT ( matrixvalue | matrixaddition | matrixmultiply ) END_OF_STATEMENT
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixassignment147);
            matrixvariable6=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixassignmentEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, matrixvariable6.tree);
            {
                ret->setLhs(matrixvariable6.ret); 
            }
            ASSIGNMENT7 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGNMENT, &FOLLOW_ASSIGNMENT_in_matrixassignment155); 
            if  (HASEXCEPTION())
            {
                goto rulematrixassignmentEx;
            }

            ASSIGNMENT7_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ASSIGNMENT7));
            ADAPTOR->addChild(ADAPTOR, root_0, ASSIGNMENT7_tree);


            // Interp.g:76:2: ( matrixvalue | matrixaddition | matrixmultiply )
            {
                int alt3=3;

                {
                    int LA3_0 = LA(1);
                    if ( (LA3_0 == MATRIXVALUE) ) 
                    {
                        alt3=1;
                    }
                    else if ( (LA3_0 == MATRIXVARIABLE) ) 
                    {

                        {
                            int LA3_2 = LA(2);
                            if ( (LA3_2 == PLUS) ) 
                            {
                                alt3=2;
                            }
                            else if ( (LA3_2 == PRODUCT) ) 
                            {
                                alt3=3;
                            }
                            else 
                            {
                            
                                CONSTRUCTEX();
                                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                                EXCEPTION->message      = (void *)"";
                                EXCEPTION->decisionNum  = 3;
                                EXCEPTION->state        = 2;


                                goto rulematrixassignmentEx;
                            }
                        }
                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 3;
                        EXCEPTION->state        = 0;


                        goto rulematrixassignmentEx;
                    }
                }
                switch (alt3) 
                {
            	case 1:
            	    // Interp.g:76:3: matrixvalue
            	    {
            	        FOLLOWPUSH(FOLLOW_matrixvalue_in_matrixassignment160);
            	        matrixvalue8=matrixvalue(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulematrixassignmentEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, matrixvalue8.tree);
            	        {
            	            ret->setRhs(matrixvalue8.ret); 
            	        }

            	    }
            	    break;
            	case 2:
            	    // Interp.g:77:4: matrixaddition
            	    {
            	        FOLLOWPUSH(FOLLOW_matrixaddition_in_matrixassignment170);
            	        matrixaddition9=matrixaddition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulematrixassignmentEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, matrixaddition9.tree);
            	        {
            	            ret->setRhs(matrixaddition9.ret);
            	        }

            	    }
            	    break;
            	case 3:
            	    // Interp.g:78:4: matrixmultiply
            	    {
            	        FOLLOWPUSH(FOLLOW_matrixmultiply_in_matrixassignment177);
            	        matrixmultiply10=matrixmultiply(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulematrixassignmentEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, matrixmultiply10.tree);
            	        {
            	            ret->setRhs(matrixmultiply10.ret);
            	        }

            	    }
            	    break;

                }
            }
            END_OF_STATEMENT11 = (pANTLR3_COMMON_TOKEN) MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_matrixassignment188); 
            if  (HASEXCEPTION())
            {
                goto rulematrixassignmentEx;
            }

            END_OF_STATEMENT11_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, END_OF_STATEMENT11));
            ADAPTOR->addChild(ADAPTOR, root_0, END_OF_STATEMENT11_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixassignmentEx; /* Prevent compiler warnings */
    rulematrixassignmentEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end matrixassignment */

/** 
 * $ANTLR start matrixaddition
 * Interp.g:82:1: matrixaddition returns [MatrixAdditionOperationElement * ret] : el1= matrixvariable '+' el2= matrixvariable ;
 */
static InterpParser_matrixaddition_return
matrixaddition(pInterpParser ctx)
{   
    InterpParser_matrixaddition_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal12;
    InterpParser_matrixvariable_return el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 InterpParser_matrixvariable_return

    InterpParser_matrixvariable_return el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 InterpParser_matrixvariable_return

    pANTLR3_BASE_TREE char_literal12_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new MatrixAdditionOperationElement();

    char_literal12       = NULL;
    el1.tree = NULL;

    el2.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    char_literal12_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:86:3: (el1= matrixvariable '+' el2= matrixvariable )
        // Interp.g:86:5: el1= matrixvariable '+' el2= matrixvariable
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixaddition212);
            el1=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixadditionEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, el1.tree);
            {
                 ret->setLhs(el1.ret); 
            }
            char_literal12 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_matrixaddition221); 
            if  (HASEXCEPTION())
            {
                goto rulematrixadditionEx;
            }

            char_literal12_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal12));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal12_tree);

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixaddition230);
            el2=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixadditionEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, el2.tree);
            {
                 ret->setRhs(el2.ret); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixadditionEx; /* Prevent compiler warnings */
    rulematrixadditionEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end matrixaddition */

/** 
 * $ANTLR start matrixmultiply
 * Interp.g:90:1: matrixmultiply returns [MatrixMultiplyOperationElement *ret] : el1= matrixvariable '*' el2= matrixvariable ;
 */
static InterpParser_matrixmultiply_return
matrixmultiply(pInterpParser ctx)
{   
    InterpParser_matrixmultiply_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal13;
    InterpParser_matrixvariable_return el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 InterpParser_matrixvariable_return

    InterpParser_matrixvariable_return el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 InterpParser_matrixvariable_return

    pANTLR3_BASE_TREE char_literal13_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


       ret=new MatrixMultiplyOperationElement();

    char_literal13       = NULL;
    el1.tree = NULL;

    el2.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    char_literal13_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:94:1: (el1= matrixvariable '*' el2= matrixvariable )
        // Interp.g:94:3: el1= matrixvariable '*' el2= matrixvariable
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixmultiply252);
            el1=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixmultiplyEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, el1.tree);
            {
                 ret->setLhs(el1.ret); 
            }
            char_literal13 = (pANTLR3_COMMON_TOKEN) MATCHT(PRODUCT, &FOLLOW_PRODUCT_in_matrixmultiply261); 
            if  (HASEXCEPTION())
            {
                goto rulematrixmultiplyEx;
            }

            char_literal13_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal13));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal13_tree);

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixmultiply268);
            el2=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixmultiplyEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, el2.tree);
            {
                 ret->setRhs(el2.ret); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixmultiplyEx; /* Prevent compiler warnings */
    rulematrixmultiplyEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end matrixmultiply */

/** 
 * $ANTLR start matrixvariable
 * Interp.g:98:1: matrixvariable returns [MatrixVariableElement * ret] : MATRIXVARIABLE ;
 */
static InterpParser_matrixvariable_return
matrixvariable(pInterpParser ctx)
{   
    InterpParser_matrixvariable_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    MATRIXVARIABLE14;

    pANTLR3_BASE_TREE MATRIXVARIABLE14_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new MatrixVariableElement();

    MATRIXVARIABLE14       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    MATRIXVARIABLE14_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:102:2: ( MATRIXVARIABLE )
        // Interp.g:102:4: MATRIXVARIABLE
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            MATRIXVARIABLE14 = (pANTLR3_COMMON_TOKEN) MATCHT(MATRIXVARIABLE, &FOLLOW_MATRIXVARIABLE_in_matrixvariable289); 
            if  (HASEXCEPTION())
            {
                goto rulematrixvariableEx;
            }

            MATRIXVARIABLE14_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MATRIXVARIABLE14));
            ADAPTOR->addChild(ADAPTOR, root_0, MATRIXVARIABLE14_tree);

            {

                				   pANTLR3_STRING str = (MATRIXVARIABLE14->getText(MATRIXVARIABLE14));
                				char * chars = (char *) str->chars;
                				std::cout<<"Matrix variable syntax matched "<<*chars;
                				ret->setText(std::string(chars));
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixvariableEx; /* Prevent compiler warnings */
    rulematrixvariableEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end matrixvariable */

/** 
 * $ANTLR start matrixvalue
 * Interp.g:108:1: matrixvalue returns [MatrixValueElement * ret] : MATRIXVALUE ;
 */
static InterpParser_matrixvalue_return
matrixvalue(pInterpParser ctx)
{   
    InterpParser_matrixvalue_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    MATRIXVALUE15;

    pANTLR3_BASE_TREE MATRIXVALUE15_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


       ret=new MatrixValueElement();

    MATRIXVALUE15       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    MATRIXVALUE15_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:112:2: ( MATRIXVALUE )
        // Interp.g:112:4: MATRIXVALUE
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            MATRIXVALUE15 = (pANTLR3_COMMON_TOKEN) MATCHT(MATRIXVALUE, &FOLLOW_MATRIXVALUE_in_matrixvalue312); 
            if  (HASEXCEPTION())
            {
                goto rulematrixvalueEx;
            }

            MATRIXVALUE15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MATRIXVALUE15));
            ADAPTOR->addChild(ADAPTOR, root_0, MATRIXVALUE15_tree);

            {
                pANTLR3_STRING str = (MATRIXVALUE15->getText(MATRIXVALUE15));
                				char * chars = (char *) str->chars;
                				std::cout<<"Matrix value syntax matched "<<*chars;
                				ret->setText(std::string(chars));
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixvalueEx; /* Prevent compiler warnings */
    rulematrixvalueEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end matrixvalue */

/** 
 * $ANTLR start matrixprint
 * Interp.g:117:1: matrixprint returns [MatrixPrintOperationElement * ret] : 'print' matrixvariable END_OF_STATEMENT ;
 */
static InterpParser_matrixprint_return
matrixprint(pInterpParser ctx)
{   
    InterpParser_matrixprint_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal16;
    pANTLR3_COMMON_TOKEN    END_OF_STATEMENT18;
    InterpParser_matrixvariable_return matrixvariable17;
    #undef	RETURN_TYPE_matrixvariable17
    #define	RETURN_TYPE_matrixvariable17 InterpParser_matrixvariable_return

    pANTLR3_BASE_TREE string_literal16_tree;
    pANTLR3_BASE_TREE END_OF_STATEMENT18_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new MatrixPrintOperationElement();

    string_literal16       = NULL;
    END_OF_STATEMENT18       = NULL;
    matrixvariable17.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    string_literal16_tree   = NULL;
    END_OF_STATEMENT18_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:121:3: ( 'print' matrixvariable END_OF_STATEMENT )
        // Interp.g:121:5: 'print' matrixvariable END_OF_STATEMENT
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            string_literal16 = (pANTLR3_COMMON_TOKEN) MATCHT(15, &FOLLOW_15_in_matrixprint334); 
            if  (HASEXCEPTION())
            {
                goto rulematrixprintEx;
            }

            string_literal16_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal16));
            ADAPTOR->addChild(ADAPTOR, root_0, string_literal16_tree);

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixprint336);
            matrixvariable17=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixprintEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, matrixvariable17.tree);
            {
                ret->setChildElement(matrixvariable17.ret); 
            }
            END_OF_STATEMENT18 = (pANTLR3_COMMON_TOKEN) MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_matrixprint344); 
            if  (HASEXCEPTION())
            {
                goto rulematrixprintEx;
            }

            END_OF_STATEMENT18_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, END_OF_STATEMENT18));
            ADAPTOR->addChild(ADAPTOR, root_0, END_OF_STATEMENT18_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixprintEx; /* Prevent compiler warnings */
    rulematrixprintEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end matrixprint */

/** 
 * $ANTLR start assignment
 * Interp.g:124:1: assignment returns [AssignmentOperationElement * ret] : variable ASSIGNMENT ( var_or_int_literal | addition | multiply ) END_OF_STATEMENT ;
 */
static InterpParser_assignment_return
assignment(pInterpParser ctx)
{   
    InterpParser_assignment_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    ASSIGNMENT20;
    pANTLR3_COMMON_TOKEN    END_OF_STATEMENT24;
    InterpParser_variable_return variable19;
    #undef	RETURN_TYPE_variable19
    #define	RETURN_TYPE_variable19 InterpParser_variable_return

    InterpParser_var_or_int_literal_return var_or_int_literal21;
    #undef	RETURN_TYPE_var_or_int_literal21
    #define	RETURN_TYPE_var_or_int_literal21 InterpParser_var_or_int_literal_return

    InterpParser_addition_return addition22;
    #undef	RETURN_TYPE_addition22
    #define	RETURN_TYPE_addition22 InterpParser_addition_return

    InterpParser_multiply_return multiply23;
    #undef	RETURN_TYPE_multiply23
    #define	RETURN_TYPE_multiply23 InterpParser_multiply_return

    pANTLR3_BASE_TREE ASSIGNMENT20_tree;
    pANTLR3_BASE_TREE END_OF_STATEMENT24_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new AssignmentOperationElement();

    ASSIGNMENT20       = NULL;
    END_OF_STATEMENT24       = NULL;
    variable19.tree = NULL;

    var_or_int_literal21.tree = NULL;

    addition22.tree = NULL;

    multiply23.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    ASSIGNMENT20_tree   = NULL;
    END_OF_STATEMENT24_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:128:3: ( variable ASSIGNMENT ( var_or_int_literal | addition | multiply ) END_OF_STATEMENT )
        // Interp.g:128:5: variable ASSIGNMENT ( var_or_int_literal | addition | multiply ) END_OF_STATEMENT
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_variable_in_assignment365);
            variable19=variable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, variable19.tree);
            {
                ret->setLhs(variable19.ret); 
            }
            ASSIGNMENT20 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGNMENT, &FOLLOW_ASSIGNMENT_in_assignment373); 
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }

            ASSIGNMENT20_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ASSIGNMENT20));
            ADAPTOR->addChild(ADAPTOR, root_0, ASSIGNMENT20_tree);


            // Interp.g:130:2: ( var_or_int_literal | addition | multiply )
            {
                int alt4=3;

                {
                    int LA4_0 = LA(1);
                    if ( (LA4_0 == VARIABLE) ) 
                    {
                        switch ( LA(2) ) 
                        {
                        case END_OF_STATEMENT:
                        	{
                        		alt4=1;
                        	}
                            break;
                        case PLUS:
                        	{
                        		alt4=2;
                        	}
                            break;
                        case PRODUCT:
                        	{
                        		alt4=3;
                        	}
                            break;

                        default:
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 4;
                            EXCEPTION->state        = 1;


                            goto ruleassignmentEx;
                        }

                    }
                    else if ( (LA4_0 == INT_LITERAL) ) 
                    {
                        switch ( LA(2) ) 
                        {
                        case PLUS:
                        	{
                        		alt4=2;
                        	}
                            break;
                        case END_OF_STATEMENT:
                        	{
                        		alt4=1;
                        	}
                            break;
                        case PRODUCT:
                        	{
                        		alt4=3;
                        	}
                            break;

                        default:
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 4;
                            EXCEPTION->state        = 2;


                            goto ruleassignmentEx;
                        }

                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 4;
                        EXCEPTION->state        = 0;


                        goto ruleassignmentEx;
                    }
                }
                switch (alt4) 
                {
            	case 1:
            	    // Interp.g:130:3: var_or_int_literal
            	    {
            	        FOLLOWPUSH(FOLLOW_var_or_int_literal_in_assignment378);
            	        var_or_int_literal21=var_or_int_literal(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, var_or_int_literal21.tree);
            	        {
            	            ret->setRhs(var_or_int_literal21.ret); 
            	        }

            	    }
            	    break;
            	case 2:
            	    // Interp.g:131:6: addition
            	    {
            	        FOLLOWPUSH(FOLLOW_addition_in_assignment390);
            	        addition22=addition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, addition22.tree);
            	        {
            	            ret->setRhs(addition22.ret);
            	        }

            	    }
            	    break;
            	case 3:
            	    // Interp.g:132:3: multiply
            	    {
            	        FOLLOWPUSH(FOLLOW_multiply_in_assignment396);
            	        multiply23=multiply(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, multiply23.tree);
            	        {
            	            ret->setRhs(multiply23.ret);
            	        }

            	    }
            	    break;

                }
            }
            END_OF_STATEMENT24 = (pANTLR3_COMMON_TOKEN) MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_assignment406); 
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }

            END_OF_STATEMENT24_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, END_OF_STATEMENT24));
            ADAPTOR->addChild(ADAPTOR, root_0, END_OF_STATEMENT24_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleassignmentEx; /* Prevent compiler warnings */
    ruleassignmentEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end assignment */

/** 
 * $ANTLR start var_or_int_literal
 * Interp.g:135:1: var_or_int_literal returns [Element * ret] : ( variable | int_literal ) ;
 */
static InterpParser_var_or_int_literal_return
var_or_int_literal(pInterpParser ctx)
{   
    InterpParser_var_or_int_literal_return retval;

    pANTLR3_BASE_TREE root_0;

    InterpParser_variable_return variable25;
    #undef	RETURN_TYPE_variable25
    #define	RETURN_TYPE_variable25 InterpParser_variable_return

    InterpParser_int_literal_return int_literal26;
    #undef	RETURN_TYPE_int_literal26
    #define	RETURN_TYPE_int_literal26 InterpParser_int_literal_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    variable25.tree = NULL;

    int_literal26.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // Interp.g:136:3: ( ( variable | int_literal ) )
        // Interp.g:136:6: ( variable | int_literal )
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // Interp.g:136:6: ( variable | int_literal )
            {
                int alt5=2;

                {
                    int LA5_0 = LA(1);
                    if ( (LA5_0 == VARIABLE) ) 
                    {
                        alt5=1;
                    }
                    else if ( (LA5_0 == INT_LITERAL) ) 
                    {
                        alt5=2;
                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 5;
                        EXCEPTION->state        = 0;


                        goto rulevar_or_int_literalEx;
                    }
                }
                switch (alt5) 
                {
            	case 1:
            	    // Interp.g:136:7: variable
            	    {
            	        FOLLOWPUSH(FOLLOW_variable_in_var_or_int_literal422);
            	        variable25=variable(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulevar_or_int_literalEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, variable25.tree);
            	        {
            	             ret = variable25.ret; 
            	        }

            	    }
            	    break;
            	case 2:
            	    // Interp.g:137:7: int_literal
            	    {
            	        FOLLOWPUSH(FOLLOW_int_literal_in_var_or_int_literal433);
            	        int_literal26=int_literal(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulevar_or_int_literalEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, int_literal26.tree);
            	        {
            	            ret = int_literal26.ret; 
            	        }

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulevar_or_int_literalEx; /* Prevent compiler warnings */
    rulevar_or_int_literalEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end var_or_int_literal */

/** 
 * $ANTLR start variable
 * Interp.g:140:1: variable returns [VariableElement * ret] : VARIABLE ;
 */
static InterpParser_variable_return
variable(pInterpParser ctx)
{   
    InterpParser_variable_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    VARIABLE27;

    pANTLR3_BASE_TREE VARIABLE27_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new VariableElement();

    VARIABLE27       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    VARIABLE27_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:144:3: ( VARIABLE )
        // Interp.g:144:5: VARIABLE
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            VARIABLE27 = (pANTLR3_COMMON_TOKEN) MATCHT(VARIABLE, &FOLLOW_VARIABLE_in_variable457); 
            if  (HASEXCEPTION())
            {
                goto rulevariableEx;
            }

            VARIABLE27_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, VARIABLE27));
            ADAPTOR->addChild(ADAPTOR, root_0, VARIABLE27_tree);

            {
                 pANTLR3_STRING str = (VARIABLE27->getText(VARIABLE27));
                	       char * chars = (char *) str->chars;
                               ret->setText(std::string(chars)); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulevariableEx; /* Prevent compiler warnings */
    rulevariableEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end variable */

/** 
 * $ANTLR start int_literal
 * Interp.g:149:1: int_literal returns [IntegerElement * ret] : INT_LITERAL ;
 */
static InterpParser_int_literal_return
int_literal(pInterpParser ctx)
{   
    InterpParser_int_literal_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT_LITERAL28;

    pANTLR3_BASE_TREE INT_LITERAL28_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new IntegerElement();

    INT_LITERAL28       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    INT_LITERAL28_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:153:3: ( INT_LITERAL )
        // Interp.g:153:5: INT_LITERAL
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            INT_LITERAL28 = (pANTLR3_COMMON_TOKEN) MATCHT(INT_LITERAL, &FOLLOW_INT_LITERAL_in_int_literal487); 
            if  (HASEXCEPTION())
            {
                goto ruleint_literalEx;
            }

            INT_LITERAL28_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT_LITERAL28));
            ADAPTOR->addChild(ADAPTOR, root_0, INT_LITERAL28_tree);

            {
                 pANTLR3_STRING str = (INT_LITERAL28->getText(INT_LITERAL28));
                	       char * chars = (char *) str->chars;
                               ret->setText(std::string(chars)); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleint_literalEx; /* Prevent compiler warnings */
    ruleint_literalEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end int_literal */

/** 
 * $ANTLR start addition
 * Interp.g:159:1: addition returns [AdditionOperationElement * ret] : el1= var_or_int_literal '+' el2= var_or_int_literal ;
 */
static InterpParser_addition_return
addition(pInterpParser ctx)
{   
    InterpParser_addition_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal29;
    InterpParser_var_or_int_literal_return el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 InterpParser_var_or_int_literal_return

    InterpParser_var_or_int_literal_return el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 InterpParser_var_or_int_literal_return

    pANTLR3_BASE_TREE char_literal29_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new AdditionOperationElement();

    char_literal29       = NULL;
    el1.tree = NULL;

    el2.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    char_literal29_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:163:3: (el1= var_or_int_literal '+' el2= var_or_int_literal )
        // Interp.g:163:5: el1= var_or_int_literal '+' el2= var_or_int_literal
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_addition524);
            el1=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, el1.tree);
            {
                 ret->setLhs(el1.ret); 
            }
            char_literal29 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_addition533); 
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }

            char_literal29_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal29));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal29_tree);

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_addition542);
            el2=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, el2.tree);
            {
                 ret->setRhs(el2.ret); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleadditionEx; /* Prevent compiler warnings */
    ruleadditionEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end addition */

/** 
 * $ANTLR start multiply
 * Interp.g:167:1: multiply returns [MultiplyOperationElement *ret] : el1= var_or_int_literal '*' el2= var_or_int_literal ;
 */
static InterpParser_multiply_return
multiply(pInterpParser ctx)
{   
    InterpParser_multiply_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal30;
    InterpParser_var_or_int_literal_return el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 InterpParser_var_or_int_literal_return

    InterpParser_var_or_int_literal_return el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 InterpParser_var_or_int_literal_return

    pANTLR3_BASE_TREE char_literal30_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


       ret=new MultiplyOperationElement();

    char_literal30       = NULL;
    el1.tree = NULL;

    el2.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    char_literal30_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:171:1: (el1= var_or_int_literal '*' el2= var_or_int_literal )
        // Interp.g:171:3: el1= var_or_int_literal '*' el2= var_or_int_literal
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_multiply564);
            el1=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultiplyEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, el1.tree);
            {
                 ret->setLhs(el1.ret); 
            }
            char_literal30 = (pANTLR3_COMMON_TOKEN) MATCHT(PRODUCT, &FOLLOW_PRODUCT_in_multiply573); 
            if  (HASEXCEPTION())
            {
                goto rulemultiplyEx;
            }

            char_literal30_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal30));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal30_tree);

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_multiply580);
            el2=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultiplyEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, el2.tree);
            {
                 ret->setRhs(el2.ret); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulemultiplyEx; /* Prevent compiler warnings */
    rulemultiplyEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end multiply */

/** 
 * $ANTLR start print
 * Interp.g:175:1: print returns [PrintOperationElement * ret] : 'print' var_or_int_literal END_OF_STATEMENT ;
 */
static InterpParser_print_return
print(pInterpParser ctx)
{   
    InterpParser_print_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal31;
    pANTLR3_COMMON_TOKEN    END_OF_STATEMENT33;
    InterpParser_var_or_int_literal_return var_or_int_literal32;
    #undef	RETURN_TYPE_var_or_int_literal32
    #define	RETURN_TYPE_var_or_int_literal32 InterpParser_var_or_int_literal_return

    pANTLR3_BASE_TREE string_literal31_tree;
    pANTLR3_BASE_TREE END_OF_STATEMENT33_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;


      ret = new PrintOperationElement();

    string_literal31       = NULL;
    END_OF_STATEMENT33       = NULL;
    var_or_int_literal32.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    string_literal31_tree   = NULL;
    END_OF_STATEMENT33_tree   = NULL;


    retval.tree  = NULL;
    {
        // Interp.g:179:3: ( 'print' var_or_int_literal END_OF_STATEMENT )
        // Interp.g:179:5: 'print' var_or_int_literal END_OF_STATEMENT
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            string_literal31 = (pANTLR3_COMMON_TOKEN) MATCHT(15, &FOLLOW_15_in_print602); 
            if  (HASEXCEPTION())
            {
                goto ruleprintEx;
            }

            string_literal31_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal31));
            ADAPTOR->addChild(ADAPTOR, root_0, string_literal31_tree);

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_print604);
            var_or_int_literal32=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprintEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, var_or_int_literal32.tree);
            {
                ret->setChildElement(var_or_int_literal32.ret); 
            }
            END_OF_STATEMENT33 = (pANTLR3_COMMON_TOKEN) MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_print612); 
            if  (HASEXCEPTION())
            {
                goto ruleprintEx;
            }

            END_OF_STATEMENT33_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, END_OF_STATEMENT33));
            ADAPTOR->addChild(ADAPTOR, root_0, END_OF_STATEMENT33_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleprintEx; /* Prevent compiler warnings */
    ruleprintEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end print */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
