/** \file
 *  This C source file was generated by $ANTLR version 3.1.3 Mar 18, 2009 10:09:25
 *
 *     -  From the grammar source file : Interp.g
 *     -                            On : 2009-10-13 22:36:53
 *     -                for the parser : InterpParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

#include <vector>
#include<iostream>
#include "Element.h"
#include "VariableElement.h"
#include "MatrixVariableElement.h"
#include "MatrixValueElement.h"
#include "MatrixAssignmentOperationElement.h"
#include "MatrixPrintOperationElement.h"
#include "MatrixMultiplyOperationElement.h"
#include "MatrixAdditionOperationElement.h"
#include "IntegerElement.h"
#include "AssignmentOperationElement.h"
#include "AdditionOperationElement.h"
#include "PrintOperationElement.h"
#include "MultiplyOperationElement.h"
#include "ParallelforOperationElement.h"

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "InterpParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pInterpParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pInterpParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pInterpParser_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   InterpParserTokenNames[18+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "WHITESPACE",
        (pANTLR3_UINT8) "RANGE",
        (pANTLR3_UINT8) "END_OF_STATEMENT",
        (pANTLR3_UINT8) "ASSIGNMENT",
        (pANTLR3_UINT8) "MATRIXVARIABLE",
        (pANTLR3_UINT8) "MATRIXVALUE",
        (pANTLR3_UINT8) "VARIABLE",
        (pANTLR3_UINT8) "INT_LITERAL",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "PRODUCT",
        (pANTLR3_UINT8) "RSQBRACKET",
        (pANTLR3_UINT8) "LSQBRACKET",
        (pANTLR3_UINT8) "'parallelfor'",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'",
        (pANTLR3_UINT8) "'print'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static std::vector<Element *> *	program    (pInterpParser ctx);
static Element *	expr    (pInterpParser ctx);
static ParallelforOperationElement *	parallelfor    (pInterpParser ctx);
static MatrixAssignmentOperationElement *	matrixassignment    (pInterpParser ctx);
static MatrixAdditionOperationElement *	matrixaddition    (pInterpParser ctx);
static MatrixMultiplyOperationElement *	matrixmultiply    (pInterpParser ctx);
static MatrixVariableElement *	matrixvariable    (pInterpParser ctx);
static MatrixValueElement *	matrixvalue    (pInterpParser ctx);
static MatrixPrintOperationElement *	matrixprint    (pInterpParser ctx);
static AssignmentOperationElement *	assignment    (pInterpParser ctx);
static Element *	var_or_int_literal    (pInterpParser ctx);
static VariableElement *	variable    (pInterpParser ctx);
static IntegerElement *	int_literal    (pInterpParser ctx);
static AdditionOperationElement *	addition    (pInterpParser ctx);
static MultiplyOperationElement *	multiply    (pInterpParser ctx);
static PrintOperationElement *	print    (pInterpParser ctx);
static void	InterpParserFree(pInterpParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "Interp.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new InterpParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pInterpParser
InterpParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return InterpParserNewSSD(instream, NULL);
}

/** \brief Create a new InterpParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pInterpParser
InterpParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pInterpParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pInterpParser) ANTLR3_CALLOC(1, sizeof(InterpParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in InterpParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our InterpParser interface
     */
    ctx->program	= program;
    ctx->expr	= expr;
    ctx->parallelfor	= parallelfor;
    ctx->matrixassignment	= matrixassignment;
    ctx->matrixaddition	= matrixaddition;
    ctx->matrixmultiply	= matrixmultiply;
    ctx->matrixvariable	= matrixvariable;
    ctx->matrixvalue	= matrixvalue;
    ctx->matrixprint	= matrixprint;
    ctx->assignment	= assignment;
    ctx->var_or_int_literal	= var_or_int_literal;
    ctx->variable	= variable;
    ctx->int_literal	= int_literal;
    ctx->addition	= addition;
    ctx->multiply	= multiply;
    ctx->print	= print;
    ctx->free			= InterpParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = InterpParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 InterpParserFree(pInterpParser ctx)
 {
    /* Free any scope memory
     */
    
        
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return InterpParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_program66  */
static	ANTLR3_BITWORD FOLLOW_expr_in_program66_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000210502) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_program66	= { FOLLOW_expr_in_program66_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignment_in_expr95  */
static	ANTLR3_BITWORD FOLLOW_assignment_in_expr95_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_assignment_in_expr95	= { FOLLOW_assignment_in_expr95_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixassignment_in_expr103  */
static	ANTLR3_BITWORD FOLLOW_matrixassignment_in_expr103_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixassignment_in_expr103	= { FOLLOW_matrixassignment_in_expr103_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_print_in_expr111  */
static	ANTLR3_BITWORD FOLLOW_print_in_expr111_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_print_in_expr111	= { FOLLOW_print_in_expr111_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixprint_in_expr119  */
static	ANTLR3_BITWORD FOLLOW_matrixprint_in_expr119_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixprint_in_expr119	= { FOLLOW_matrixprint_in_expr119_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_parallelfor_in_expr127  */
static	ANTLR3_BITWORD FOLLOW_parallelfor_in_expr127_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_parallelfor_in_expr127	= { FOLLOW_parallelfor_in_expr127_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_parallelfor147  */
static	ANTLR3_BITWORD FOLLOW_16_in_parallelfor147_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_parallelfor147	= { FOLLOW_16_in_parallelfor147_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_parallelfor149  */
static	ANTLR3_BITWORD FOLLOW_17_in_parallelfor149_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_parallelfor149	= { FOLLOW_17_in_parallelfor149_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_variable_in_parallelfor155  */
static	ANTLR3_BITWORD FOLLOW_variable_in_parallelfor155_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_variable_in_parallelfor155	= { FOLLOW_variable_in_parallelfor155_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHITESPACE_in_parallelfor161  */
static	ANTLR3_BITWORD FOLLOW_WHITESPACE_in_parallelfor161_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_WHITESPACE_in_parallelfor161	= { FOLLOW_WHITESPACE_in_parallelfor161_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RANGE_in_parallelfor164  */
static	ANTLR3_BITWORD FOLLOW_RANGE_in_parallelfor164_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_RANGE_in_parallelfor164	= { FOLLOW_RANGE_in_parallelfor164_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_parallelfor173  */
static	ANTLR3_BITWORD FOLLOW_18_in_parallelfor173_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_parallelfor173	= { FOLLOW_18_in_parallelfor173_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_parallelfor176  */
static	ANTLR3_BITWORD FOLLOW_19_in_parallelfor176_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_parallelfor176	= { FOLLOW_19_in_parallelfor176_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignment_in_parallelfor181  */
static	ANTLR3_BITWORD FOLLOW_assignment_in_parallelfor181_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100400) };
static  ANTLR3_BITSET_LIST FOLLOW_assignment_in_parallelfor181	= { FOLLOW_assignment_in_parallelfor181_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_parallelfor188  */
static	ANTLR3_BITWORD FOLLOW_20_in_parallelfor188_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_parallelfor188	= { FOLLOW_20_in_parallelfor188_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_parallelfor191  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_parallelfor191_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_parallelfor191	= { FOLLOW_END_OF_STATEMENT_in_parallelfor191_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixassignment213  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixassignment213_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixassignment213	= { FOLLOW_matrixvariable_in_matrixassignment213_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGNMENT_in_matrixassignment221  */
static	ANTLR3_BITWORD FOLLOW_ASSIGNMENT_in_matrixassignment221_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGNMENT_in_matrixassignment221	= { FOLLOW_ASSIGNMENT_in_matrixassignment221_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvalue_in_matrixassignment226  */
static	ANTLR3_BITWORD FOLLOW_matrixvalue_in_matrixassignment226_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvalue_in_matrixassignment226	= { FOLLOW_matrixvalue_in_matrixassignment226_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixaddition_in_matrixassignment236  */
static	ANTLR3_BITWORD FOLLOW_matrixaddition_in_matrixassignment236_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixaddition_in_matrixassignment236	= { FOLLOW_matrixaddition_in_matrixassignment236_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixmultiply_in_matrixassignment243  */
static	ANTLR3_BITWORD FOLLOW_matrixmultiply_in_matrixassignment243_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixmultiply_in_matrixassignment243	= { FOLLOW_matrixmultiply_in_matrixassignment243_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_matrixassignment254  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_matrixassignment254_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_matrixassignment254	= { FOLLOW_END_OF_STATEMENT_in_matrixassignment254_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixaddition278  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixaddition278_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixaddition278	= { FOLLOW_matrixvariable_in_matrixaddition278_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_matrixaddition287  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_matrixaddition287_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_matrixaddition287	= { FOLLOW_PLUS_in_matrixaddition287_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixaddition296  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixaddition296_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixaddition296	= { FOLLOW_matrixvariable_in_matrixaddition296_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixmultiply318  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixmultiply318_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixmultiply318	= { FOLLOW_matrixvariable_in_matrixmultiply318_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRODUCT_in_matrixmultiply327  */
static	ANTLR3_BITWORD FOLLOW_PRODUCT_in_matrixmultiply327_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_PRODUCT_in_matrixmultiply327	= { FOLLOW_PRODUCT_in_matrixmultiply327_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixmultiply334  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixmultiply334_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixmultiply334	= { FOLLOW_matrixvariable_in_matrixmultiply334_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MATRIXVARIABLE_in_matrixvariable355  */
static	ANTLR3_BITWORD FOLLOW_MATRIXVARIABLE_in_matrixvariable355_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_MATRIXVARIABLE_in_matrixvariable355	= { FOLLOW_MATRIXVARIABLE_in_matrixvariable355_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MATRIXVALUE_in_matrixvalue378  */
static	ANTLR3_BITWORD FOLLOW_MATRIXVALUE_in_matrixvalue378_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_MATRIXVALUE_in_matrixvalue378	= { FOLLOW_MATRIXVALUE_in_matrixvalue378_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_matrixprint400  */
static	ANTLR3_BITWORD FOLLOW_21_in_matrixprint400_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_matrixprint400	= { FOLLOW_21_in_matrixprint400_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixprint402  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixprint402_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixprint402	= { FOLLOW_matrixvariable_in_matrixprint402_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_matrixprint410  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_matrixprint410_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_matrixprint410	= { FOLLOW_END_OF_STATEMENT_in_matrixprint410_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_variable_in_assignment431  */
static	ANTLR3_BITWORD FOLLOW_variable_in_assignment431_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_variable_in_assignment431	= { FOLLOW_variable_in_assignment431_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGNMENT_in_assignment439  */
static	ANTLR3_BITWORD FOLLOW_ASSIGNMENT_in_assignment439_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000C00) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGNMENT_in_assignment439	= { FOLLOW_ASSIGNMENT_in_assignment439_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_assignment444  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_assignment444_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_assignment444	= { FOLLOW_var_or_int_literal_in_assignment444_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_addition_in_assignment456  */
static	ANTLR3_BITWORD FOLLOW_addition_in_assignment456_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_addition_in_assignment456	= { FOLLOW_addition_in_assignment456_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multiply_in_assignment462  */
static	ANTLR3_BITWORD FOLLOW_multiply_in_assignment462_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_multiply_in_assignment462	= { FOLLOW_multiply_in_assignment462_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_assignment472  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_assignment472_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_assignment472	= { FOLLOW_END_OF_STATEMENT_in_assignment472_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_variable_in_var_or_int_literal488  */
static	ANTLR3_BITWORD FOLLOW_variable_in_var_or_int_literal488_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_variable_in_var_or_int_literal488	= { FOLLOW_variable_in_var_or_int_literal488_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_int_literal_in_var_or_int_literal499  */
static	ANTLR3_BITWORD FOLLOW_int_literal_in_var_or_int_literal499_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_int_literal_in_var_or_int_literal499	= { FOLLOW_int_literal_in_var_or_int_literal499_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_VARIABLE_in_variable523  */
static	ANTLR3_BITWORD FOLLOW_VARIABLE_in_variable523_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_VARIABLE_in_variable523	= { FOLLOW_VARIABLE_in_variable523_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_LITERAL_in_int_literal553  */
static	ANTLR3_BITWORD FOLLOW_INT_LITERAL_in_int_literal553_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_LITERAL_in_int_literal553	= { FOLLOW_INT_LITERAL_in_int_literal553_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_addition590  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_addition590_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_addition590	= { FOLLOW_var_or_int_literal_in_addition590_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_addition599  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_addition599_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000C00) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_addition599	= { FOLLOW_PLUS_in_addition599_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_addition608  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_addition608_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_addition608	= { FOLLOW_var_or_int_literal_in_addition608_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_multiply630  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_multiply630_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_multiply630	= { FOLLOW_var_or_int_literal_in_multiply630_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRODUCT_in_multiply639  */
static	ANTLR3_BITWORD FOLLOW_PRODUCT_in_multiply639_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000C00) };
static  ANTLR3_BITSET_LIST FOLLOW_PRODUCT_in_multiply639	= { FOLLOW_PRODUCT_in_multiply639_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_multiply646  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_multiply646_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_multiply646	= { FOLLOW_var_or_int_literal_in_multiply646_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_print668  */
static	ANTLR3_BITWORD FOLLOW_21_in_print668_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000C00) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_print668	= { FOLLOW_21_in_print668_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_print670  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_print670_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_print670	= { FOLLOW_var_or_int_literal_in_print670_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_print678  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_print678_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_print678	= { FOLLOW_END_OF_STATEMENT_in_print678_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start program
 * Interp.g:58:1: program returns [std::vector<Element *> * ret] : ( expr )+ ;
 */
static std::vector<Element *> *
program(pInterpParser ctx)
{   
    std::vector<Element *> * ret = NULL;

    Element * expr1;
    #undef	RETURN_TYPE_expr1
    #define	RETURN_TYPE_expr1 Element *

    /* Initialize rule variables
     */



      ret = new std::vector<Element *>();

    expr1 = NULL;

    {
        // Interp.g:62:3: ( ( expr )+ )
        // Interp.g:62:5: ( expr )+
        {
            // Interp.g:62:5: ( expr )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA1_0 = LA(1);
            	    if ( (LA1_0 == MATRIXVARIABLE || LA1_0 == VARIABLE || LA1_0 == 16 || LA1_0 == 21) ) 
            	    {
            	        alt1=1;
            	    }

            	}
            	switch (alt1) 
            	{
            	    case 1:
            	        // Interp.g:62:6: expr
            	        {
            	            FOLLOWPUSH(FOLLOW_expr_in_program66);
            	            expr1=expr(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogramEx;
            	            }

            	            {
            	                ret->push_back(expr1); 
            	            }

            	        }
            	        break;

            	    default:
            	    
            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogramEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleprogramEx; /* Prevent compiler warnings */
    ruleprogramEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end program */

/** 
 * $ANTLR start expr
 * Interp.g:67:1: expr returns [Element * ret] : ( assignment | matrixassignment | print | matrixprint | parallelfor );
 */
static Element *
expr(pInterpParser ctx)
{   
    Element * ret = NULL;

    AssignmentOperationElement * assignment2;
    #undef	RETURN_TYPE_assignment2
    #define	RETURN_TYPE_assignment2 AssignmentOperationElement *

    MatrixAssignmentOperationElement * matrixassignment3;
    #undef	RETURN_TYPE_matrixassignment3
    #define	RETURN_TYPE_matrixassignment3 MatrixAssignmentOperationElement *

    PrintOperationElement * print4;
    #undef	RETURN_TYPE_print4
    #define	RETURN_TYPE_print4 PrintOperationElement *

    MatrixPrintOperationElement * matrixprint5;
    #undef	RETURN_TYPE_matrixprint5
    #define	RETURN_TYPE_matrixprint5 MatrixPrintOperationElement *

    ParallelforOperationElement * parallelfor6;
    #undef	RETURN_TYPE_parallelfor6
    #define	RETURN_TYPE_parallelfor6 ParallelforOperationElement *

    /* Initialize rule variables
     */


    assignment2 = NULL;
    matrixassignment3 = NULL;
    print4 = NULL;
    matrixprint5 = NULL;
    parallelfor6 = NULL;

    {
        {
            //  Interp.g:68:3: ( assignment | matrixassignment | print | matrixprint | parallelfor )
            
            ANTLR3_UINT32 alt2;

            alt2=5;

            switch ( LA(1) ) 
            {
            case VARIABLE:
            	{
            		alt2=1;
            	}
                break;
            case MATRIXVARIABLE:
            	{
            		alt2=2;
            	}
                break;
            case 21:
            	{

            		{
            		    int LA2_3 = LA(2);
            		    if ( (((LA2_3 >= VARIABLE) && (LA2_3 <= INT_LITERAL))) ) 
            		    {
            		        alt2=3;
            		    }
            		    else if ( (LA2_3 == MATRIXVARIABLE) ) 
            		    {
            		        alt2=4;
            		    }
            		    else 
            		    {
            		    
            		        CONSTRUCTEX();
            		        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		        EXCEPTION->message      = (void *)"";
            		        EXCEPTION->decisionNum  = 2;
            		        EXCEPTION->state        = 3;


            		        goto ruleexprEx;
            		    }
            		}
            	}
                break;
            case 16:
            	{
            		alt2=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto ruleexprEx;
            }

            switch (alt2) 
            {
        	case 1:
        	    // Interp.g:68:5: assignment
        	    {
        	        FOLLOWPUSH(FOLLOW_assignment_in_expr95);
        	        assignment2=assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {
        	            ret = assignment2;
        	        }

        	    }
        	    break;
        	case 2:
        	    // Interp.g:69:5: matrixassignment
        	    {
        	        FOLLOWPUSH(FOLLOW_matrixassignment_in_expr103);
        	        matrixassignment3=matrixassignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {
        	            ret=matrixassignment3;
        	        }

        	    }
        	    break;
        	case 3:
        	    // Interp.g:70:5: print
        	    {
        	        FOLLOWPUSH(FOLLOW_print_in_expr111);
        	        print4=print(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {
        	             ret = print4; 
        	        }

        	    }
        	    break;
        	case 4:
        	    // Interp.g:71:5: matrixprint
        	    {
        	        FOLLOWPUSH(FOLLOW_matrixprint_in_expr119);
        	        matrixprint5=matrixprint(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {
        	             ret = matrixprint5; 
        	        }

        	    }
        	    break;
        	case 5:
        	    // Interp.g:72:5: parallelfor
        	    {
        	        FOLLOWPUSH(FOLLOW_parallelfor_in_expr127);
        	        parallelfor6=parallelfor(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {
        	             ret = parallelfor6; 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end expr */

/** 
 * $ANTLR start parallelfor
 * Interp.g:74:1: parallelfor returns [ParallelforOperationElement * ret] : 'parallelfor' '(' variable WHITESPACE RANGE ')' '{' ( assignment )+ '}' END_OF_STATEMENT ;
 */
static ParallelforOperationElement *
parallelfor(pInterpParser ctx)
{   
    ParallelforOperationElement * ret = NULL;

    pANTLR3_COMMON_TOKEN    RANGE8;
    VariableElement * variable7;
    #undef	RETURN_TYPE_variable7
    #define	RETURN_TYPE_variable7 VariableElement *

    AssignmentOperationElement * assignment9;
    #undef	RETURN_TYPE_assignment9
    #define	RETURN_TYPE_assignment9 AssignmentOperationElement *

    /* Initialize rule variables
     */



    	ret=new ParallelforOperationElement();

    RANGE8       = NULL;
    variable7 = NULL;
    assignment9 = NULL;

    {
        // Interp.g:78:2: ( 'parallelfor' '(' variable WHITESPACE RANGE ')' '{' ( assignment )+ '}' END_OF_STATEMENT )
        // Interp.g:78:4: 'parallelfor' '(' variable WHITESPACE RANGE ')' '{' ( assignment )+ '}' END_OF_STATEMENT
        {
             MATCHT(16, &FOLLOW_16_in_parallelfor147); 
            if  (HASEXCEPTION())
            {
                goto ruleparallelforEx;
            }

             MATCHT(17, &FOLLOW_17_in_parallelfor149); 
            if  (HASEXCEPTION())
            {
                goto ruleparallelforEx;
            }

            FOLLOWPUSH(FOLLOW_variable_in_parallelfor155);
            variable7=variable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleparallelforEx;
            }

            {
                ret->setIndexVariableName(variable7);
            }
             MATCHT(WHITESPACE, &FOLLOW_WHITESPACE_in_parallelfor161); 
            if  (HASEXCEPTION())
            {
                goto ruleparallelforEx;
            }

            RANGE8 = (pANTLR3_COMMON_TOKEN) MATCHT(RANGE, &FOLLOW_RANGE_in_parallelfor164); 
            if  (HASEXCEPTION())
            {
                goto ruleparallelforEx;
            }

            {
                pANTLR3_STRING str = (RANGE8->getText(RANGE8));
                	       char * chars = (char *) str->chars;
                               ret->setIndexRange(std::string(chars)); 
            }
             MATCHT(18, &FOLLOW_18_in_parallelfor173); 
            if  (HASEXCEPTION())
            {
                goto ruleparallelforEx;
            }

             MATCHT(19, &FOLLOW_19_in_parallelfor176); 
            if  (HASEXCEPTION())
            {
                goto ruleparallelforEx;
            }

            // Interp.g:86:3: ( assignment )+
            {
                int cnt3=0;

                for (;;)
                {
                    int alt3=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA3_0 = LA(1);
            	    if ( (LA3_0 == VARIABLE) ) 
            	    {
            	        alt3=1;
            	    }

            	}
            	switch (alt3) 
            	{
            	    case 1:
            	        // Interp.g:86:4: assignment
            	        {
            	            FOLLOWPUSH(FOLLOW_assignment_in_parallelfor181);
            	            assignment9=assignment(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleparallelforEx;
            	            }

            	            {
            	                ret->setBody(assignment9);
            	            }

            	        }
            	        break;

            	    default:
            	    
            		if ( cnt3 >= 1 )
            		{
            		    goto loop3;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleparallelforEx;
            	}
            	cnt3++;
                }
                loop3: ;	/* Jump to here if this rule does not match */
            }
             MATCHT(20, &FOLLOW_20_in_parallelfor188); 
            if  (HASEXCEPTION())
            {
                goto ruleparallelforEx;
            }

             MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_parallelfor191); 
            if  (HASEXCEPTION())
            {
                goto ruleparallelforEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleparallelforEx; /* Prevent compiler warnings */
    ruleparallelforEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end parallelfor */

/** 
 * $ANTLR start matrixassignment
 * Interp.g:90:1: matrixassignment returns [MatrixAssignmentOperationElement * ret] : matrixvariable ASSIGNMENT ( matrixvalue | matrixaddition | matrixmultiply ) END_OF_STATEMENT ;
 */
static MatrixAssignmentOperationElement *
matrixassignment(pInterpParser ctx)
{   
    MatrixAssignmentOperationElement * ret = NULL;

    MatrixVariableElement * matrixvariable10;
    #undef	RETURN_TYPE_matrixvariable10
    #define	RETURN_TYPE_matrixvariable10 MatrixVariableElement *

    MatrixValueElement * matrixvalue11;
    #undef	RETURN_TYPE_matrixvalue11
    #define	RETURN_TYPE_matrixvalue11 MatrixValueElement *

    MatrixAdditionOperationElement * matrixaddition12;
    #undef	RETURN_TYPE_matrixaddition12
    #define	RETURN_TYPE_matrixaddition12 MatrixAdditionOperationElement *

    MatrixMultiplyOperationElement * matrixmultiply13;
    #undef	RETURN_TYPE_matrixmultiply13
    #define	RETURN_TYPE_matrixmultiply13 MatrixMultiplyOperationElement *

    /* Initialize rule variables
     */



      ret = new MatrixAssignmentOperationElement();

    matrixvariable10 = NULL;
    matrixvalue11 = NULL;
    matrixaddition12 = NULL;
    matrixmultiply13 = NULL;

    {
        // Interp.g:94:3: ( matrixvariable ASSIGNMENT ( matrixvalue | matrixaddition | matrixmultiply ) END_OF_STATEMENT )
        // Interp.g:94:5: matrixvariable ASSIGNMENT ( matrixvalue | matrixaddition | matrixmultiply ) END_OF_STATEMENT
        {
            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixassignment213);
            matrixvariable10=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixassignmentEx;
            }

            {
                ret->setLhs(matrixvariable10); 
            }
             MATCHT(ASSIGNMENT, &FOLLOW_ASSIGNMENT_in_matrixassignment221); 
            if  (HASEXCEPTION())
            {
                goto rulematrixassignmentEx;
            }


            // Interp.g:96:2: ( matrixvalue | matrixaddition | matrixmultiply )
            {
                int alt4=3;

                {
                    int LA4_0 = LA(1);
                    if ( (LA4_0 == MATRIXVALUE) ) 
                    {
                        alt4=1;
                    }
                    else if ( (LA4_0 == MATRIXVARIABLE) ) 
                    {

                        {
                            int LA4_2 = LA(2);
                            if ( (LA4_2 == PRODUCT) ) 
                            {
                                alt4=3;
                            }
                            else if ( (LA4_2 == PLUS) ) 
                            {
                                alt4=2;
                            }
                            else 
                            {
                            
                                CONSTRUCTEX();
                                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                                EXCEPTION->message      = (void *)"";
                                EXCEPTION->decisionNum  = 4;
                                EXCEPTION->state        = 2;


                                goto rulematrixassignmentEx;
                            }
                        }
                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 4;
                        EXCEPTION->state        = 0;


                        goto rulematrixassignmentEx;
                    }
                }
                switch (alt4) 
                {
            	case 1:
            	    // Interp.g:96:3: matrixvalue
            	    {
            	        FOLLOWPUSH(FOLLOW_matrixvalue_in_matrixassignment226);
            	        matrixvalue11=matrixvalue(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulematrixassignmentEx;
            	        }

            	        {
            	            ret->setRhs(matrixvalue11); 
            	        }

            	    }
            	    break;
            	case 2:
            	    // Interp.g:97:4: matrixaddition
            	    {
            	        FOLLOWPUSH(FOLLOW_matrixaddition_in_matrixassignment236);
            	        matrixaddition12=matrixaddition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulematrixassignmentEx;
            	        }

            	        {
            	            ret->setRhs(matrixaddition12);
            	        }

            	    }
            	    break;
            	case 3:
            	    // Interp.g:98:4: matrixmultiply
            	    {
            	        FOLLOWPUSH(FOLLOW_matrixmultiply_in_matrixassignment243);
            	        matrixmultiply13=matrixmultiply(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulematrixassignmentEx;
            	        }

            	        {
            	            ret->setRhs(matrixmultiply13);
            	        }

            	    }
            	    break;

                }
            }
             MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_matrixassignment254); 
            if  (HASEXCEPTION())
            {
                goto rulematrixassignmentEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixassignmentEx; /* Prevent compiler warnings */
    rulematrixassignmentEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixassignment */

/** 
 * $ANTLR start matrixaddition
 * Interp.g:102:1: matrixaddition returns [MatrixAdditionOperationElement * ret] : el1= matrixvariable '+' el2= matrixvariable ;
 */
static MatrixAdditionOperationElement *
matrixaddition(pInterpParser ctx)
{   
    MatrixAdditionOperationElement * ret = NULL;

    MatrixVariableElement * el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 MatrixVariableElement *

    MatrixVariableElement * el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 MatrixVariableElement *

    /* Initialize rule variables
     */



      ret = new MatrixAdditionOperationElement();

    el1 = NULL;
    el2 = NULL;

    {
        // Interp.g:106:3: (el1= matrixvariable '+' el2= matrixvariable )
        // Interp.g:106:5: el1= matrixvariable '+' el2= matrixvariable
        {
            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixaddition278);
            el1=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixadditionEx;
            }

            {
                 ret->setLhs(el1); 
            }
             MATCHT(PLUS, &FOLLOW_PLUS_in_matrixaddition287); 
            if  (HASEXCEPTION())
            {
                goto rulematrixadditionEx;
            }

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixaddition296);
            el2=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixadditionEx;
            }

            {
                 ret->setRhs(el2); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixadditionEx; /* Prevent compiler warnings */
    rulematrixadditionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixaddition */

/** 
 * $ANTLR start matrixmultiply
 * Interp.g:110:1: matrixmultiply returns [MatrixMultiplyOperationElement *ret] : el1= matrixvariable '*' el2= matrixvariable ;
 */
static MatrixMultiplyOperationElement *
matrixmultiply(pInterpParser ctx)
{   
    MatrixMultiplyOperationElement * ret = NULL;

    MatrixVariableElement * el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 MatrixVariableElement *

    MatrixVariableElement * el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 MatrixVariableElement *

    /* Initialize rule variables
     */



       ret=new MatrixMultiplyOperationElement();

    el1 = NULL;
    el2 = NULL;

    {
        // Interp.g:114:1: (el1= matrixvariable '*' el2= matrixvariable )
        // Interp.g:114:3: el1= matrixvariable '*' el2= matrixvariable
        {
            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixmultiply318);
            el1=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixmultiplyEx;
            }

            {
                 ret->setLhs(el1); 
            }
             MATCHT(PRODUCT, &FOLLOW_PRODUCT_in_matrixmultiply327); 
            if  (HASEXCEPTION())
            {
                goto rulematrixmultiplyEx;
            }

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixmultiply334);
            el2=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixmultiplyEx;
            }

            {
                 ret->setRhs(el2); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixmultiplyEx; /* Prevent compiler warnings */
    rulematrixmultiplyEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixmultiply */

/** 
 * $ANTLR start matrixvariable
 * Interp.g:118:1: matrixvariable returns [MatrixVariableElement * ret] : MATRIXVARIABLE ;
 */
static MatrixVariableElement *
matrixvariable(pInterpParser ctx)
{   
    MatrixVariableElement * ret = NULL;

    pANTLR3_COMMON_TOKEN    MATRIXVARIABLE14;

    /* Initialize rule variables
     */



      ret = new MatrixVariableElement();

    MATRIXVARIABLE14       = NULL;

    {
        // Interp.g:122:2: ( MATRIXVARIABLE )
        // Interp.g:122:4: MATRIXVARIABLE
        {
            MATRIXVARIABLE14 = (pANTLR3_COMMON_TOKEN) MATCHT(MATRIXVARIABLE, &FOLLOW_MATRIXVARIABLE_in_matrixvariable355); 
            if  (HASEXCEPTION())
            {
                goto rulematrixvariableEx;
            }

            {

                				   pANTLR3_STRING str = (MATRIXVARIABLE14->getText(MATRIXVARIABLE14));
                				char * chars = (char *) str->chars;
                				ret->setText(std::string(chars));
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixvariableEx; /* Prevent compiler warnings */
    rulematrixvariableEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixvariable */

/** 
 * $ANTLR start matrixvalue
 * Interp.g:127:1: matrixvalue returns [MatrixValueElement * ret] : MATRIXVALUE ;
 */
static MatrixValueElement *
matrixvalue(pInterpParser ctx)
{   
    MatrixValueElement * ret = NULL;

    pANTLR3_COMMON_TOKEN    MATRIXVALUE15;

    /* Initialize rule variables
     */



       ret=new MatrixValueElement();

    MATRIXVALUE15       = NULL;

    {
        // Interp.g:131:2: ( MATRIXVALUE )
        // Interp.g:131:4: MATRIXVALUE
        {
            MATRIXVALUE15 = (pANTLR3_COMMON_TOKEN) MATCHT(MATRIXVALUE, &FOLLOW_MATRIXVALUE_in_matrixvalue378); 
            if  (HASEXCEPTION())
            {
                goto rulematrixvalueEx;
            }

            {
                pANTLR3_STRING str = (MATRIXVALUE15->getText(MATRIXVALUE15));
                				char * chars = (char *) str->chars;
                				ret->setText(std::string(chars));
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixvalueEx; /* Prevent compiler warnings */
    rulematrixvalueEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixvalue */

/** 
 * $ANTLR start matrixprint
 * Interp.g:135:1: matrixprint returns [MatrixPrintOperationElement * ret] : 'print' matrixvariable END_OF_STATEMENT ;
 */
static MatrixPrintOperationElement *
matrixprint(pInterpParser ctx)
{   
    MatrixPrintOperationElement * ret = NULL;

    MatrixVariableElement * matrixvariable16;
    #undef	RETURN_TYPE_matrixvariable16
    #define	RETURN_TYPE_matrixvariable16 MatrixVariableElement *

    /* Initialize rule variables
     */



      ret = new MatrixPrintOperationElement();

    matrixvariable16 = NULL;

    {
        // Interp.g:139:3: ( 'print' matrixvariable END_OF_STATEMENT )
        // Interp.g:139:5: 'print' matrixvariable END_OF_STATEMENT
        {
             MATCHT(21, &FOLLOW_21_in_matrixprint400); 
            if  (HASEXCEPTION())
            {
                goto rulematrixprintEx;
            }

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixprint402);
            matrixvariable16=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixprintEx;
            }

            {
                ret->setChildElement(matrixvariable16); 
            }
             MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_matrixprint410); 
            if  (HASEXCEPTION())
            {
                goto rulematrixprintEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixprintEx; /* Prevent compiler warnings */
    rulematrixprintEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixprint */

/** 
 * $ANTLR start assignment
 * Interp.g:142:1: assignment returns [AssignmentOperationElement * ret] : variable ASSIGNMENT ( var_or_int_literal | addition | multiply ) END_OF_STATEMENT ;
 */
static AssignmentOperationElement *
assignment(pInterpParser ctx)
{   
    AssignmentOperationElement * ret = NULL;

    VariableElement * variable17;
    #undef	RETURN_TYPE_variable17
    #define	RETURN_TYPE_variable17 VariableElement *

    Element * var_or_int_literal18;
    #undef	RETURN_TYPE_var_or_int_literal18
    #define	RETURN_TYPE_var_or_int_literal18 Element *

    AdditionOperationElement * addition19;
    #undef	RETURN_TYPE_addition19
    #define	RETURN_TYPE_addition19 AdditionOperationElement *

    MultiplyOperationElement * multiply20;
    #undef	RETURN_TYPE_multiply20
    #define	RETURN_TYPE_multiply20 MultiplyOperationElement *

    /* Initialize rule variables
     */



      ret = new AssignmentOperationElement();

    variable17 = NULL;
    var_or_int_literal18 = NULL;
    addition19 = NULL;
    multiply20 = NULL;

    {
        // Interp.g:146:3: ( variable ASSIGNMENT ( var_or_int_literal | addition | multiply ) END_OF_STATEMENT )
        // Interp.g:146:5: variable ASSIGNMENT ( var_or_int_literal | addition | multiply ) END_OF_STATEMENT
        {
            FOLLOWPUSH(FOLLOW_variable_in_assignment431);
            variable17=variable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }

            {
                ret->setLhs(variable17); 
            }
             MATCHT(ASSIGNMENT, &FOLLOW_ASSIGNMENT_in_assignment439); 
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }


            // Interp.g:148:2: ( var_or_int_literal | addition | multiply )
            {
                int alt5=3;

                {
                    int LA5_0 = LA(1);
                    if ( (LA5_0 == VARIABLE) ) 
                    {
                        switch ( LA(2) ) 
                        {
                        case END_OF_STATEMENT:
                        	{
                        		alt5=1;
                        	}
                            break;
                        case PLUS:
                        	{
                        		alt5=2;
                        	}
                            break;
                        case PRODUCT:
                        	{
                        		alt5=3;
                        	}
                            break;

                        default:
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 5;
                            EXCEPTION->state        = 1;


                            goto ruleassignmentEx;
                        }

                    }
                    else if ( (LA5_0 == INT_LITERAL) ) 
                    {
                        switch ( LA(2) ) 
                        {
                        case PRODUCT:
                        	{
                        		alt5=3;
                        	}
                            break;
                        case END_OF_STATEMENT:
                        	{
                        		alt5=1;
                        	}
                            break;
                        case PLUS:
                        	{
                        		alt5=2;
                        	}
                            break;

                        default:
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 5;
                            EXCEPTION->state        = 2;


                            goto ruleassignmentEx;
                        }

                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 5;
                        EXCEPTION->state        = 0;


                        goto ruleassignmentEx;
                    }
                }
                switch (alt5) 
                {
            	case 1:
            	    // Interp.g:148:3: var_or_int_literal
            	    {
            	        FOLLOWPUSH(FOLLOW_var_or_int_literal_in_assignment444);
            	        var_or_int_literal18=var_or_int_literal(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }

            	        {
            	            ret->setRhs(var_or_int_literal18); 
            	        }

            	    }
            	    break;
            	case 2:
            	    // Interp.g:149:6: addition
            	    {
            	        FOLLOWPUSH(FOLLOW_addition_in_assignment456);
            	        addition19=addition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }

            	        {
            	            ret->setRhs(addition19);
            	        }

            	    }
            	    break;
            	case 3:
            	    // Interp.g:150:3: multiply
            	    {
            	        FOLLOWPUSH(FOLLOW_multiply_in_assignment462);
            	        multiply20=multiply(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }

            	        {
            	            ret->setRhs(multiply20);
            	        }

            	    }
            	    break;

                }
            }
             MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_assignment472); 
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleassignmentEx; /* Prevent compiler warnings */
    ruleassignmentEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end assignment */

/** 
 * $ANTLR start var_or_int_literal
 * Interp.g:153:1: var_or_int_literal returns [Element * ret] : ( variable | int_literal ) ;
 */
static Element *
var_or_int_literal(pInterpParser ctx)
{   
    Element * ret = NULL;

    VariableElement * variable21;
    #undef	RETURN_TYPE_variable21
    #define	RETURN_TYPE_variable21 VariableElement *

    IntegerElement * int_literal22;
    #undef	RETURN_TYPE_int_literal22
    #define	RETURN_TYPE_int_literal22 IntegerElement *

    /* Initialize rule variables
     */


    variable21 = NULL;
    int_literal22 = NULL;

    {
        // Interp.g:154:3: ( ( variable | int_literal ) )
        // Interp.g:154:6: ( variable | int_literal )
        {

            // Interp.g:154:6: ( variable | int_literal )
            {
                int alt6=2;

                {
                    int LA6_0 = LA(1);
                    if ( (LA6_0 == VARIABLE) ) 
                    {
                        alt6=1;
                    }
                    else if ( (LA6_0 == INT_LITERAL) ) 
                    {
                        alt6=2;
                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 6;
                        EXCEPTION->state        = 0;


                        goto rulevar_or_int_literalEx;
                    }
                }
                switch (alt6) 
                {
            	case 1:
            	    // Interp.g:154:7: variable
            	    {
            	        FOLLOWPUSH(FOLLOW_variable_in_var_or_int_literal488);
            	        variable21=variable(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulevar_or_int_literalEx;
            	        }

            	        {
            	             ret = variable21; 
            	        }

            	    }
            	    break;
            	case 2:
            	    // Interp.g:155:7: int_literal
            	    {
            	        FOLLOWPUSH(FOLLOW_int_literal_in_var_or_int_literal499);
            	        int_literal22=int_literal(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulevar_or_int_literalEx;
            	        }

            	        {
            	            ret = int_literal22; 
            	        }

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulevar_or_int_literalEx; /* Prevent compiler warnings */
    rulevar_or_int_literalEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end var_or_int_literal */

/** 
 * $ANTLR start variable
 * Interp.g:158:1: variable returns [VariableElement * ret] : VARIABLE ;
 */
static VariableElement *
variable(pInterpParser ctx)
{   
    VariableElement * ret = NULL;

    pANTLR3_COMMON_TOKEN    VARIABLE23;

    /* Initialize rule variables
     */



      ret = new VariableElement();

    VARIABLE23       = NULL;

    {
        // Interp.g:162:3: ( VARIABLE )
        // Interp.g:162:5: VARIABLE
        {
            VARIABLE23 = (pANTLR3_COMMON_TOKEN) MATCHT(VARIABLE, &FOLLOW_VARIABLE_in_variable523); 
            if  (HASEXCEPTION())
            {
                goto rulevariableEx;
            }

            {
                 pANTLR3_STRING str = (VARIABLE23->getText(VARIABLE23));
                	       char * chars = (char *) str->chars;
                               ret->setText(std::string(chars)); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulevariableEx; /* Prevent compiler warnings */
    rulevariableEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end variable */

/** 
 * $ANTLR start int_literal
 * Interp.g:167:1: int_literal returns [IntegerElement * ret] : INT_LITERAL ;
 */
static IntegerElement *
int_literal(pInterpParser ctx)
{   
    IntegerElement * ret = NULL;

    pANTLR3_COMMON_TOKEN    INT_LITERAL24;

    /* Initialize rule variables
     */



      ret = new IntegerElement();

    INT_LITERAL24       = NULL;

    {
        // Interp.g:171:3: ( INT_LITERAL )
        // Interp.g:171:5: INT_LITERAL
        {
            INT_LITERAL24 = (pANTLR3_COMMON_TOKEN) MATCHT(INT_LITERAL, &FOLLOW_INT_LITERAL_in_int_literal553); 
            if  (HASEXCEPTION())
            {
                goto ruleint_literalEx;
            }

            {
                 pANTLR3_STRING str = (INT_LITERAL24->getText(INT_LITERAL24));
                	       char * chars = (char *) str->chars;
                               ret->setText(std::string(chars)); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleint_literalEx; /* Prevent compiler warnings */
    ruleint_literalEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end int_literal */

/** 
 * $ANTLR start addition
 * Interp.g:177:1: addition returns [AdditionOperationElement * ret] : el1= var_or_int_literal '+' el2= var_or_int_literal ;
 */
static AdditionOperationElement *
addition(pInterpParser ctx)
{   
    AdditionOperationElement * ret = NULL;

    Element * el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 Element *

    Element * el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 Element *

    /* Initialize rule variables
     */



      ret = new AdditionOperationElement();

    el1 = NULL;
    el2 = NULL;

    {
        // Interp.g:181:3: (el1= var_or_int_literal '+' el2= var_or_int_literal )
        // Interp.g:181:5: el1= var_or_int_literal '+' el2= var_or_int_literal
        {
            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_addition590);
            el1=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }

            {
                 ret->setLhs(el1); 
            }
             MATCHT(PLUS, &FOLLOW_PLUS_in_addition599); 
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_addition608);
            el2=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }

            {
                 ret->setRhs(el2); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleadditionEx; /* Prevent compiler warnings */
    ruleadditionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end addition */

/** 
 * $ANTLR start multiply
 * Interp.g:185:1: multiply returns [MultiplyOperationElement *ret] : el1= var_or_int_literal '*' el2= var_or_int_literal ;
 */
static MultiplyOperationElement *
multiply(pInterpParser ctx)
{   
    MultiplyOperationElement * ret = NULL;

    Element * el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 Element *

    Element * el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 Element *

    /* Initialize rule variables
     */



       ret=new MultiplyOperationElement();

    el1 = NULL;
    el2 = NULL;

    {
        // Interp.g:189:1: (el1= var_or_int_literal '*' el2= var_or_int_literal )
        // Interp.g:189:3: el1= var_or_int_literal '*' el2= var_or_int_literal
        {
            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_multiply630);
            el1=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultiplyEx;
            }

            {
                 ret->setLhs(el1); 
            }
             MATCHT(PRODUCT, &FOLLOW_PRODUCT_in_multiply639); 
            if  (HASEXCEPTION())
            {
                goto rulemultiplyEx;
            }

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_multiply646);
            el2=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultiplyEx;
            }

            {
                 ret->setRhs(el2); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulemultiplyEx; /* Prevent compiler warnings */
    rulemultiplyEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end multiply */

/** 
 * $ANTLR start print
 * Interp.g:193:1: print returns [PrintOperationElement * ret] : 'print' var_or_int_literal END_OF_STATEMENT ;
 */
static PrintOperationElement *
print(pInterpParser ctx)
{   
    PrintOperationElement * ret = NULL;

    Element * var_or_int_literal25;
    #undef	RETURN_TYPE_var_or_int_literal25
    #define	RETURN_TYPE_var_or_int_literal25 Element *

    /* Initialize rule variables
     */



      ret = new PrintOperationElement();

    var_or_int_literal25 = NULL;

    {
        // Interp.g:197:3: ( 'print' var_or_int_literal END_OF_STATEMENT )
        // Interp.g:197:5: 'print' var_or_int_literal END_OF_STATEMENT
        {
             MATCHT(21, &FOLLOW_21_in_print668); 
            if  (HASEXCEPTION())
            {
                goto ruleprintEx;
            }

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_print670);
            var_or_int_literal25=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprintEx;
            }

            {
                ret->setChildElement(var_or_int_literal25); 
            }
             MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_print678); 
            if  (HASEXCEPTION())
            {
                goto ruleprintEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleprintEx; /* Prevent compiler warnings */
    ruleprintEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end print */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
