/** \file
 *  This C source file was generated by $ANTLR version 3.1.3 Mar 18, 2009 10:09:25
 *
 *     -  From the grammar source file : Interp.g
 *     -                            On : 2009-10-10 16:19:20
 *     -                for the parser : InterpParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

#include <vector>
#include<iostream>
#include "Element.h"
#include "VariableElement.h"
#include "MatrixVariableElement.h"
#include "MatrixValueElement.h"
#include "MatrixAssignmentOperationElement.h"
#include "MatrixPrintOperationElement.h"
#include "MatrixMultiplyOperationElement.h"
#include "MatrixAdditionOperationElement.h"
#include "IntegerElement.h"
#include "AssignmentOperationElement.h"
#include "AdditionOperationElement.h"
#include "PrintOperationElement.h"
#include "MultiplyOperationElement.h"

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "InterpParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pInterpParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pInterpParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pInterpParser_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   InterpParserTokenNames[12+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "ASSIGNMENT",
        (pANTLR3_UINT8) "END_OF_STATEMENT",
        (pANTLR3_UINT8) "MATRIXVARIABLE",
        (pANTLR3_UINT8) "MATRIXVALUE",
        (pANTLR3_UINT8) "VARIABLE",
        (pANTLR3_UINT8) "INT_LITERAL",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "PRODUCT",
        (pANTLR3_UINT8) "RSQBRACKET",
        (pANTLR3_UINT8) "LSQBRACKET",
        (pANTLR3_UINT8) "WHITESPACE",
        (pANTLR3_UINT8) "'print'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static std::vector<Element *> *	program    (pInterpParser ctx);
static Element *	expr    (pInterpParser ctx);
static MatrixAssignmentOperationElement *	matrixassignment    (pInterpParser ctx);
static MatrixAdditionOperationElement *	matrixaddition    (pInterpParser ctx);
static MatrixMultiplyOperationElement *	matrixmultiply    (pInterpParser ctx);
static MatrixVariableElement *	matrixvariable    (pInterpParser ctx);
static MatrixValueElement *	matrixvalue    (pInterpParser ctx);
static MatrixPrintOperationElement *	matrixprint    (pInterpParser ctx);
static AssignmentOperationElement *	assignment    (pInterpParser ctx);
static Element *	var_or_int_literal    (pInterpParser ctx);
static VariableElement *	variable    (pInterpParser ctx);
static IntegerElement *	int_literal    (pInterpParser ctx);
static AdditionOperationElement *	addition    (pInterpParser ctx);
static MultiplyOperationElement *	multiply    (pInterpParser ctx);
static PrintOperationElement *	print    (pInterpParser ctx);
static void	InterpParserFree(pInterpParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "Interp.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new InterpParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pInterpParser
InterpParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return InterpParserNewSSD(instream, NULL);
}

/** \brief Create a new InterpParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pInterpParser
InterpParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pInterpParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pInterpParser) ANTLR3_CALLOC(1, sizeof(InterpParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in InterpParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our InterpParser interface
     */
    ctx->program	= program;
    ctx->expr	= expr;
    ctx->matrixassignment	= matrixassignment;
    ctx->matrixaddition	= matrixaddition;
    ctx->matrixmultiply	= matrixmultiply;
    ctx->matrixvariable	= matrixvariable;
    ctx->matrixvalue	= matrixvalue;
    ctx->matrixprint	= matrixprint;
    ctx->assignment	= assignment;
    ctx->var_or_int_literal	= var_or_int_literal;
    ctx->variable	= variable;
    ctx->int_literal	= int_literal;
    ctx->addition	= addition;
    ctx->multiply	= multiply;
    ctx->print	= print;
    ctx->free			= InterpParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = InterpParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 InterpParserFree(pInterpParser ctx)
 {
    /* Free any scope memory
     */
    
        
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return InterpParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_program66  */
static	ANTLR3_BITWORD FOLLOW_expr_in_program66_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008142) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_program66	= { FOLLOW_expr_in_program66_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignment_in_expr91  */
static	ANTLR3_BITWORD FOLLOW_assignment_in_expr91_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_assignment_in_expr91	= { FOLLOW_assignment_in_expr91_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixassignment_in_expr99  */
static	ANTLR3_BITWORD FOLLOW_matrixassignment_in_expr99_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixassignment_in_expr99	= { FOLLOW_matrixassignment_in_expr99_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_print_in_expr107  */
static	ANTLR3_BITWORD FOLLOW_print_in_expr107_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_print_in_expr107	= { FOLLOW_print_in_expr107_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixprint_in_expr115  */
static	ANTLR3_BITWORD FOLLOW_matrixprint_in_expr115_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixprint_in_expr115	= { FOLLOW_matrixprint_in_expr115_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixassignment138  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixassignment138_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixassignment138	= { FOLLOW_matrixvariable_in_matrixassignment138_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGNMENT_in_matrixassignment146  */
static	ANTLR3_BITWORD FOLLOW_ASSIGNMENT_in_matrixassignment146_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000000C0) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGNMENT_in_matrixassignment146	= { FOLLOW_ASSIGNMENT_in_matrixassignment146_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvalue_in_matrixassignment151  */
static	ANTLR3_BITWORD FOLLOW_matrixvalue_in_matrixassignment151_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvalue_in_matrixassignment151	= { FOLLOW_matrixvalue_in_matrixassignment151_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixaddition_in_matrixassignment161  */
static	ANTLR3_BITWORD FOLLOW_matrixaddition_in_matrixassignment161_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixaddition_in_matrixassignment161	= { FOLLOW_matrixaddition_in_matrixassignment161_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixmultiply_in_matrixassignment168  */
static	ANTLR3_BITWORD FOLLOW_matrixmultiply_in_matrixassignment168_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixmultiply_in_matrixassignment168	= { FOLLOW_matrixmultiply_in_matrixassignment168_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_matrixassignment179  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_matrixassignment179_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_matrixassignment179	= { FOLLOW_END_OF_STATEMENT_in_matrixassignment179_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixaddition203  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixaddition203_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixaddition203	= { FOLLOW_matrixvariable_in_matrixaddition203_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_matrixaddition212  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_matrixaddition212_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_matrixaddition212	= { FOLLOW_PLUS_in_matrixaddition212_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixaddition221  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixaddition221_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixaddition221	= { FOLLOW_matrixvariable_in_matrixaddition221_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixmultiply243  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixmultiply243_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixmultiply243	= { FOLLOW_matrixvariable_in_matrixmultiply243_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRODUCT_in_matrixmultiply252  */
static	ANTLR3_BITWORD FOLLOW_PRODUCT_in_matrixmultiply252_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_PRODUCT_in_matrixmultiply252	= { FOLLOW_PRODUCT_in_matrixmultiply252_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixmultiply259  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixmultiply259_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixmultiply259	= { FOLLOW_matrixvariable_in_matrixmultiply259_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MATRIXVARIABLE_in_matrixvariable280  */
static	ANTLR3_BITWORD FOLLOW_MATRIXVARIABLE_in_matrixvariable280_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_MATRIXVARIABLE_in_matrixvariable280	= { FOLLOW_MATRIXVARIABLE_in_matrixvariable280_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MATRIXVALUE_in_matrixvalue303  */
static	ANTLR3_BITWORD FOLLOW_MATRIXVALUE_in_matrixvalue303_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_MATRIXVALUE_in_matrixvalue303	= { FOLLOW_MATRIXVALUE_in_matrixvalue303_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_matrixprint325  */
static	ANTLR3_BITWORD FOLLOW_15_in_matrixprint325_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_matrixprint325	= { FOLLOW_15_in_matrixprint325_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_matrixvariable_in_matrixprint327  */
static	ANTLR3_BITWORD FOLLOW_matrixvariable_in_matrixprint327_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_matrixvariable_in_matrixprint327	= { FOLLOW_matrixvariable_in_matrixprint327_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_matrixprint335  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_matrixprint335_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_matrixprint335	= { FOLLOW_END_OF_STATEMENT_in_matrixprint335_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_variable_in_assignment356  */
static	ANTLR3_BITWORD FOLLOW_variable_in_assignment356_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_variable_in_assignment356	= { FOLLOW_variable_in_assignment356_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGNMENT_in_assignment364  */
static	ANTLR3_BITWORD FOLLOW_ASSIGNMENT_in_assignment364_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGNMENT_in_assignment364	= { FOLLOW_ASSIGNMENT_in_assignment364_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_assignment369  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_assignment369_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_assignment369	= { FOLLOW_var_or_int_literal_in_assignment369_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_addition_in_assignment381  */
static	ANTLR3_BITWORD FOLLOW_addition_in_assignment381_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_addition_in_assignment381	= { FOLLOW_addition_in_assignment381_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multiply_in_assignment387  */
static	ANTLR3_BITWORD FOLLOW_multiply_in_assignment387_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_multiply_in_assignment387	= { FOLLOW_multiply_in_assignment387_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_assignment397  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_assignment397_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_assignment397	= { FOLLOW_END_OF_STATEMENT_in_assignment397_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_variable_in_var_or_int_literal413  */
static	ANTLR3_BITWORD FOLLOW_variable_in_var_or_int_literal413_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_variable_in_var_or_int_literal413	= { FOLLOW_variable_in_var_or_int_literal413_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_int_literal_in_var_or_int_literal424  */
static	ANTLR3_BITWORD FOLLOW_int_literal_in_var_or_int_literal424_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_int_literal_in_var_or_int_literal424	= { FOLLOW_int_literal_in_var_or_int_literal424_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_VARIABLE_in_variable448  */
static	ANTLR3_BITWORD FOLLOW_VARIABLE_in_variable448_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_VARIABLE_in_variable448	= { FOLLOW_VARIABLE_in_variable448_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_LITERAL_in_int_literal478  */
static	ANTLR3_BITWORD FOLLOW_INT_LITERAL_in_int_literal478_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_LITERAL_in_int_literal478	= { FOLLOW_INT_LITERAL_in_int_literal478_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_addition515  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_addition515_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_addition515	= { FOLLOW_var_or_int_literal_in_addition515_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_addition524  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_addition524_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_addition524	= { FOLLOW_PLUS_in_addition524_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_addition533  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_addition533_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_addition533	= { FOLLOW_var_or_int_literal_in_addition533_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_multiply555  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_multiply555_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_multiply555	= { FOLLOW_var_or_int_literal_in_multiply555_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRODUCT_in_multiply564  */
static	ANTLR3_BITWORD FOLLOW_PRODUCT_in_multiply564_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_PRODUCT_in_multiply564	= { FOLLOW_PRODUCT_in_multiply564_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_multiply571  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_multiply571_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_multiply571	= { FOLLOW_var_or_int_literal_in_multiply571_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_print593  */
static	ANTLR3_BITWORD FOLLOW_15_in_print593_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000300) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_print593	= { FOLLOW_15_in_print593_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_var_or_int_literal_in_print595  */
static	ANTLR3_BITWORD FOLLOW_var_or_int_literal_in_print595_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_var_or_int_literal_in_print595	= { FOLLOW_var_or_int_literal_in_print595_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_END_OF_STATEMENT_in_print603  */
static	ANTLR3_BITWORD FOLLOW_END_OF_STATEMENT_in_print603_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_END_OF_STATEMENT_in_print603	= { FOLLOW_END_OF_STATEMENT_in_print603_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start program
 * Interp.g:56:1: program returns [std::vector<Element *> * ret] : ( expr )+ ;
 */
static std::vector<Element *> *
program(pInterpParser ctx)
{   
    std::vector<Element *> * ret = NULL;

    Element * expr1;
    #undef	RETURN_TYPE_expr1
    #define	RETURN_TYPE_expr1 Element *

    /* Initialize rule variables
     */



      ret = new std::vector<Element *>();

    expr1 = NULL;

    {
        // Interp.g:60:3: ( ( expr )+ )
        // Interp.g:60:5: ( expr )+
        {
            // Interp.g:60:5: ( expr )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA1_0 = LA(1);
            	    if ( (LA1_0 == MATRIXVARIABLE || LA1_0 == VARIABLE || LA1_0 == 15) ) 
            	    {
            	        alt1=1;
            	    }

            	}
            	switch (alt1) 
            	{
            	    case 1:
            	        // Interp.g:60:6: expr
            	        {
            	            FOLLOWPUSH(FOLLOW_expr_in_program66);
            	            expr1=expr(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogramEx;
            	            }

            	            {
            	                ret->push_back(expr1); 
            	            }

            	        }
            	        break;

            	    default:
            	    
            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogramEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleprogramEx; /* Prevent compiler warnings */
    ruleprogramEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end program */

/** 
 * $ANTLR start expr
 * Interp.g:64:1: expr returns [Element * ret] : ( assignment | matrixassignment | print | matrixprint );
 */
static Element *
expr(pInterpParser ctx)
{   
    Element * ret = NULL;

    AssignmentOperationElement * assignment2;
    #undef	RETURN_TYPE_assignment2
    #define	RETURN_TYPE_assignment2 AssignmentOperationElement *

    MatrixAssignmentOperationElement * matrixassignment3;
    #undef	RETURN_TYPE_matrixassignment3
    #define	RETURN_TYPE_matrixassignment3 MatrixAssignmentOperationElement *

    PrintOperationElement * print4;
    #undef	RETURN_TYPE_print4
    #define	RETURN_TYPE_print4 PrintOperationElement *

    MatrixPrintOperationElement * matrixprint5;
    #undef	RETURN_TYPE_matrixprint5
    #define	RETURN_TYPE_matrixprint5 MatrixPrintOperationElement *

    /* Initialize rule variables
     */


    assignment2 = NULL;
    matrixassignment3 = NULL;
    print4 = NULL;
    matrixprint5 = NULL;

    {
        {
            //  Interp.g:65:3: ( assignment | matrixassignment | print | matrixprint )
            
            ANTLR3_UINT32 alt2;

            alt2=4;

            switch ( LA(1) ) 
            {
            case VARIABLE:
            	{
            		alt2=1;
            	}
                break;
            case MATRIXVARIABLE:
            	{
            		alt2=2;
            	}
                break;
            case 15:
            	{

            		{
            		    int LA2_3 = LA(2);
            		    if ( (((LA2_3 >= VARIABLE) && (LA2_3 <= INT_LITERAL))) ) 
            		    {
            		        alt2=3;
            		    }
            		    else if ( (LA2_3 == MATRIXVARIABLE) ) 
            		    {
            		        alt2=4;
            		    }
            		    else 
            		    {
            		    
            		        CONSTRUCTEX();
            		        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		        EXCEPTION->message      = (void *)"";
            		        EXCEPTION->decisionNum  = 2;
            		        EXCEPTION->state        = 3;


            		        goto ruleexprEx;
            		    }
            		}
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto ruleexprEx;
            }

            switch (alt2) 
            {
        	case 1:
        	    // Interp.g:65:5: assignment
        	    {
        	        FOLLOWPUSH(FOLLOW_assignment_in_expr91);
        	        assignment2=assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {
        	            ret = assignment2;
        	        }

        	    }
        	    break;
        	case 2:
        	    // Interp.g:66:5: matrixassignment
        	    {
        	        FOLLOWPUSH(FOLLOW_matrixassignment_in_expr99);
        	        matrixassignment3=matrixassignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {
        	            ret=matrixassignment3;
        	        }

        	    }
        	    break;
        	case 3:
        	    // Interp.g:67:5: print
        	    {
        	        FOLLOWPUSH(FOLLOW_print_in_expr107);
        	        print4=print(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {
        	             ret = print4; 
        	        }

        	    }
        	    break;
        	case 4:
        	    // Interp.g:68:5: matrixprint
        	    {
        	        FOLLOWPUSH(FOLLOW_matrixprint_in_expr115);
        	        matrixprint5=matrixprint(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {
        	            ret = matrixprint5; 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end expr */

/** 
 * $ANTLR start matrixassignment
 * Interp.g:70:1: matrixassignment returns [MatrixAssignmentOperationElement * ret] : matrixvariable ASSIGNMENT ( matrixvalue | matrixaddition | matrixmultiply ) END_OF_STATEMENT ;
 */
static MatrixAssignmentOperationElement *
matrixassignment(pInterpParser ctx)
{   
    MatrixAssignmentOperationElement * ret = NULL;

    MatrixVariableElement * matrixvariable6;
    #undef	RETURN_TYPE_matrixvariable6
    #define	RETURN_TYPE_matrixvariable6 MatrixVariableElement *

    MatrixValueElement * matrixvalue7;
    #undef	RETURN_TYPE_matrixvalue7
    #define	RETURN_TYPE_matrixvalue7 MatrixValueElement *

    MatrixAdditionOperationElement * matrixaddition8;
    #undef	RETURN_TYPE_matrixaddition8
    #define	RETURN_TYPE_matrixaddition8 MatrixAdditionOperationElement *

    MatrixMultiplyOperationElement * matrixmultiply9;
    #undef	RETURN_TYPE_matrixmultiply9
    #define	RETURN_TYPE_matrixmultiply9 MatrixMultiplyOperationElement *

    /* Initialize rule variables
     */



      ret = new MatrixAssignmentOperationElement();

    matrixvariable6 = NULL;
    matrixvalue7 = NULL;
    matrixaddition8 = NULL;
    matrixmultiply9 = NULL;

    {
        // Interp.g:74:3: ( matrixvariable ASSIGNMENT ( matrixvalue | matrixaddition | matrixmultiply ) END_OF_STATEMENT )
        // Interp.g:74:5: matrixvariable ASSIGNMENT ( matrixvalue | matrixaddition | matrixmultiply ) END_OF_STATEMENT
        {
            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixassignment138);
            matrixvariable6=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixassignmentEx;
            }

            {
                ret->setLhs(matrixvariable6); 
            }
             MATCHT(ASSIGNMENT, &FOLLOW_ASSIGNMENT_in_matrixassignment146); 
            if  (HASEXCEPTION())
            {
                goto rulematrixassignmentEx;
            }


            // Interp.g:76:2: ( matrixvalue | matrixaddition | matrixmultiply )
            {
                int alt3=3;

                {
                    int LA3_0 = LA(1);
                    if ( (LA3_0 == MATRIXVALUE) ) 
                    {
                        alt3=1;
                    }
                    else if ( (LA3_0 == MATRIXVARIABLE) ) 
                    {

                        {
                            int LA3_2 = LA(2);
                            if ( (LA3_2 == PLUS) ) 
                            {
                                alt3=2;
                            }
                            else if ( (LA3_2 == PRODUCT) ) 
                            {
                                alt3=3;
                            }
                            else 
                            {
                            
                                CONSTRUCTEX();
                                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                                EXCEPTION->message      = (void *)"";
                                EXCEPTION->decisionNum  = 3;
                                EXCEPTION->state        = 2;


                                goto rulematrixassignmentEx;
                            }
                        }
                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 3;
                        EXCEPTION->state        = 0;


                        goto rulematrixassignmentEx;
                    }
                }
                switch (alt3) 
                {
            	case 1:
            	    // Interp.g:76:3: matrixvalue
            	    {
            	        FOLLOWPUSH(FOLLOW_matrixvalue_in_matrixassignment151);
            	        matrixvalue7=matrixvalue(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulematrixassignmentEx;
            	        }

            	        {
            	            ret->setRhs(matrixvalue7); 
            	        }

            	    }
            	    break;
            	case 2:
            	    // Interp.g:77:4: matrixaddition
            	    {
            	        FOLLOWPUSH(FOLLOW_matrixaddition_in_matrixassignment161);
            	        matrixaddition8=matrixaddition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulematrixassignmentEx;
            	        }

            	        {
            	            ret->setRhs(matrixaddition8);
            	        }

            	    }
            	    break;
            	case 3:
            	    // Interp.g:78:4: matrixmultiply
            	    {
            	        FOLLOWPUSH(FOLLOW_matrixmultiply_in_matrixassignment168);
            	        matrixmultiply9=matrixmultiply(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulematrixassignmentEx;
            	        }

            	        {
            	            ret->setRhs(matrixmultiply9);
            	        }

            	    }
            	    break;

                }
            }
             MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_matrixassignment179); 
            if  (HASEXCEPTION())
            {
                goto rulematrixassignmentEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixassignmentEx; /* Prevent compiler warnings */
    rulematrixassignmentEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixassignment */

/** 
 * $ANTLR start matrixaddition
 * Interp.g:82:1: matrixaddition returns [MatrixAdditionOperationElement * ret] : el1= matrixvariable '+' el2= matrixvariable ;
 */
static MatrixAdditionOperationElement *
matrixaddition(pInterpParser ctx)
{   
    MatrixAdditionOperationElement * ret = NULL;

    MatrixVariableElement * el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 MatrixVariableElement *

    MatrixVariableElement * el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 MatrixVariableElement *

    /* Initialize rule variables
     */



      ret = new MatrixAdditionOperationElement();

    el1 = NULL;
    el2 = NULL;

    {
        // Interp.g:86:3: (el1= matrixvariable '+' el2= matrixvariable )
        // Interp.g:86:5: el1= matrixvariable '+' el2= matrixvariable
        {
            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixaddition203);
            el1=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixadditionEx;
            }

            {
                 ret->setLhs(el1); 
            }
             MATCHT(PLUS, &FOLLOW_PLUS_in_matrixaddition212); 
            if  (HASEXCEPTION())
            {
                goto rulematrixadditionEx;
            }

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixaddition221);
            el2=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixadditionEx;
            }

            {
                 ret->setRhs(el2); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixadditionEx; /* Prevent compiler warnings */
    rulematrixadditionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixaddition */

/** 
 * $ANTLR start matrixmultiply
 * Interp.g:90:1: matrixmultiply returns [MatrixMultiplyOperationElement *ret] : el1= matrixvariable '*' el2= matrixvariable ;
 */
static MatrixMultiplyOperationElement *
matrixmultiply(pInterpParser ctx)
{   
    MatrixMultiplyOperationElement * ret = NULL;

    MatrixVariableElement * el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 MatrixVariableElement *

    MatrixVariableElement * el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 MatrixVariableElement *

    /* Initialize rule variables
     */



       ret=new MatrixMultiplyOperationElement();

    el1 = NULL;
    el2 = NULL;

    {
        // Interp.g:94:1: (el1= matrixvariable '*' el2= matrixvariable )
        // Interp.g:94:3: el1= matrixvariable '*' el2= matrixvariable
        {
            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixmultiply243);
            el1=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixmultiplyEx;
            }

            {
                 ret->setLhs(el1); 
            }
             MATCHT(PRODUCT, &FOLLOW_PRODUCT_in_matrixmultiply252); 
            if  (HASEXCEPTION())
            {
                goto rulematrixmultiplyEx;
            }

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixmultiply259);
            el2=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixmultiplyEx;
            }

            {
                 ret->setRhs(el2); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixmultiplyEx; /* Prevent compiler warnings */
    rulematrixmultiplyEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixmultiply */

/** 
 * $ANTLR start matrixvariable
 * Interp.g:98:1: matrixvariable returns [MatrixVariableElement * ret] : MATRIXVARIABLE ;
 */
static MatrixVariableElement *
matrixvariable(pInterpParser ctx)
{   
    MatrixVariableElement * ret = NULL;

    pANTLR3_COMMON_TOKEN    MATRIXVARIABLE10;

    /* Initialize rule variables
     */



      ret = new MatrixVariableElement();

    MATRIXVARIABLE10       = NULL;

    {
        // Interp.g:102:2: ( MATRIXVARIABLE )
        // Interp.g:102:4: MATRIXVARIABLE
        {
            MATRIXVARIABLE10 = (pANTLR3_COMMON_TOKEN) MATCHT(MATRIXVARIABLE, &FOLLOW_MATRIXVARIABLE_in_matrixvariable280); 
            if  (HASEXCEPTION())
            {
                goto rulematrixvariableEx;
            }

            {

                				   pANTLR3_STRING str = (MATRIXVARIABLE10->getText(MATRIXVARIABLE10));
                				char * chars = (char *) str->chars;
                				std::cout<<"Matrix variable syntax matched "<<*chars;
                				ret->setText(std::string(chars));
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixvariableEx; /* Prevent compiler warnings */
    rulematrixvariableEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixvariable */

/** 
 * $ANTLR start matrixvalue
 * Interp.g:108:1: matrixvalue returns [MatrixValueElement * ret] : MATRIXVALUE ;
 */
static MatrixValueElement *
matrixvalue(pInterpParser ctx)
{   
    MatrixValueElement * ret = NULL;

    pANTLR3_COMMON_TOKEN    MATRIXVALUE11;

    /* Initialize rule variables
     */



       ret=new MatrixValueElement();

    MATRIXVALUE11       = NULL;

    {
        // Interp.g:112:2: ( MATRIXVALUE )
        // Interp.g:112:4: MATRIXVALUE
        {
            MATRIXVALUE11 = (pANTLR3_COMMON_TOKEN) MATCHT(MATRIXVALUE, &FOLLOW_MATRIXVALUE_in_matrixvalue303); 
            if  (HASEXCEPTION())
            {
                goto rulematrixvalueEx;
            }

            {
                pANTLR3_STRING str = (MATRIXVALUE11->getText(MATRIXVALUE11));
                				char * chars = (char *) str->chars;
                				std::cout<<"Matrix value syntax matched "<<*chars;
                				ret->setText(std::string(chars));
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixvalueEx; /* Prevent compiler warnings */
    rulematrixvalueEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixvalue */

/** 
 * $ANTLR start matrixprint
 * Interp.g:117:1: matrixprint returns [MatrixPrintOperationElement * ret] : 'print' matrixvariable END_OF_STATEMENT ;
 */
static MatrixPrintOperationElement *
matrixprint(pInterpParser ctx)
{   
    MatrixPrintOperationElement * ret = NULL;

    MatrixVariableElement * matrixvariable12;
    #undef	RETURN_TYPE_matrixvariable12
    #define	RETURN_TYPE_matrixvariable12 MatrixVariableElement *

    /* Initialize rule variables
     */



      ret = new MatrixPrintOperationElement();

    matrixvariable12 = NULL;

    {
        // Interp.g:121:3: ( 'print' matrixvariable END_OF_STATEMENT )
        // Interp.g:121:5: 'print' matrixvariable END_OF_STATEMENT
        {
             MATCHT(15, &FOLLOW_15_in_matrixprint325); 
            if  (HASEXCEPTION())
            {
                goto rulematrixprintEx;
            }

            FOLLOWPUSH(FOLLOW_matrixvariable_in_matrixprint327);
            matrixvariable12=matrixvariable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulematrixprintEx;
            }

            {
                ret->setChildElement(matrixvariable12); 
            }
             MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_matrixprint335); 
            if  (HASEXCEPTION())
            {
                goto rulematrixprintEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulematrixprintEx; /* Prevent compiler warnings */
    rulematrixprintEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end matrixprint */

/** 
 * $ANTLR start assignment
 * Interp.g:124:1: assignment returns [AssignmentOperationElement * ret] : variable ASSIGNMENT ( var_or_int_literal | addition | multiply ) END_OF_STATEMENT ;
 */
static AssignmentOperationElement *
assignment(pInterpParser ctx)
{   
    AssignmentOperationElement * ret = NULL;

    VariableElement * variable13;
    #undef	RETURN_TYPE_variable13
    #define	RETURN_TYPE_variable13 VariableElement *

    Element * var_or_int_literal14;
    #undef	RETURN_TYPE_var_or_int_literal14
    #define	RETURN_TYPE_var_or_int_literal14 Element *

    AdditionOperationElement * addition15;
    #undef	RETURN_TYPE_addition15
    #define	RETURN_TYPE_addition15 AdditionOperationElement *

    MultiplyOperationElement * multiply16;
    #undef	RETURN_TYPE_multiply16
    #define	RETURN_TYPE_multiply16 MultiplyOperationElement *

    /* Initialize rule variables
     */



      ret = new AssignmentOperationElement();

    variable13 = NULL;
    var_or_int_literal14 = NULL;
    addition15 = NULL;
    multiply16 = NULL;

    {
        // Interp.g:128:3: ( variable ASSIGNMENT ( var_or_int_literal | addition | multiply ) END_OF_STATEMENT )
        // Interp.g:128:5: variable ASSIGNMENT ( var_or_int_literal | addition | multiply ) END_OF_STATEMENT
        {
            FOLLOWPUSH(FOLLOW_variable_in_assignment356);
            variable13=variable(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }

            {
                ret->setLhs(variable13); 
            }
             MATCHT(ASSIGNMENT, &FOLLOW_ASSIGNMENT_in_assignment364); 
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }


            // Interp.g:130:2: ( var_or_int_literal | addition | multiply )
            {
                int alt4=3;

                {
                    int LA4_0 = LA(1);
                    if ( (LA4_0 == VARIABLE) ) 
                    {
                        switch ( LA(2) ) 
                        {
                        case END_OF_STATEMENT:
                        	{
                        		alt4=1;
                        	}
                            break;
                        case PLUS:
                        	{
                        		alt4=2;
                        	}
                            break;
                        case PRODUCT:
                        	{
                        		alt4=3;
                        	}
                            break;

                        default:
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 4;
                            EXCEPTION->state        = 1;


                            goto ruleassignmentEx;
                        }

                    }
                    else if ( (LA4_0 == INT_LITERAL) ) 
                    {
                        switch ( LA(2) ) 
                        {
                        case PLUS:
                        	{
                        		alt4=2;
                        	}
                            break;
                        case END_OF_STATEMENT:
                        	{
                        		alt4=1;
                        	}
                            break;
                        case PRODUCT:
                        	{
                        		alt4=3;
                        	}
                            break;

                        default:
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 4;
                            EXCEPTION->state        = 2;


                            goto ruleassignmentEx;
                        }

                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 4;
                        EXCEPTION->state        = 0;


                        goto ruleassignmentEx;
                    }
                }
                switch (alt4) 
                {
            	case 1:
            	    // Interp.g:130:3: var_or_int_literal
            	    {
            	        FOLLOWPUSH(FOLLOW_var_or_int_literal_in_assignment369);
            	        var_or_int_literal14=var_or_int_literal(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }

            	        {
            	            ret->setRhs(var_or_int_literal14); 
            	        }

            	    }
            	    break;
            	case 2:
            	    // Interp.g:131:6: addition
            	    {
            	        FOLLOWPUSH(FOLLOW_addition_in_assignment381);
            	        addition15=addition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }

            	        {
            	            ret->setRhs(addition15);
            	        }

            	    }
            	    break;
            	case 3:
            	    // Interp.g:132:3: multiply
            	    {
            	        FOLLOWPUSH(FOLLOW_multiply_in_assignment387);
            	        multiply16=multiply(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }

            	        {
            	            ret->setRhs(multiply16);
            	        }

            	    }
            	    break;

                }
            }
             MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_assignment397); 
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleassignmentEx; /* Prevent compiler warnings */
    ruleassignmentEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end assignment */

/** 
 * $ANTLR start var_or_int_literal
 * Interp.g:135:1: var_or_int_literal returns [Element * ret] : ( variable | int_literal ) ;
 */
static Element *
var_or_int_literal(pInterpParser ctx)
{   
    Element * ret = NULL;

    VariableElement * variable17;
    #undef	RETURN_TYPE_variable17
    #define	RETURN_TYPE_variable17 VariableElement *

    IntegerElement * int_literal18;
    #undef	RETURN_TYPE_int_literal18
    #define	RETURN_TYPE_int_literal18 IntegerElement *

    /* Initialize rule variables
     */


    variable17 = NULL;
    int_literal18 = NULL;

    {
        // Interp.g:136:3: ( ( variable | int_literal ) )
        // Interp.g:136:6: ( variable | int_literal )
        {

            // Interp.g:136:6: ( variable | int_literal )
            {
                int alt5=2;

                {
                    int LA5_0 = LA(1);
                    if ( (LA5_0 == VARIABLE) ) 
                    {
                        alt5=1;
                    }
                    else if ( (LA5_0 == INT_LITERAL) ) 
                    {
                        alt5=2;
                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 5;
                        EXCEPTION->state        = 0;


                        goto rulevar_or_int_literalEx;
                    }
                }
                switch (alt5) 
                {
            	case 1:
            	    // Interp.g:136:7: variable
            	    {
            	        FOLLOWPUSH(FOLLOW_variable_in_var_or_int_literal413);
            	        variable17=variable(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulevar_or_int_literalEx;
            	        }

            	        {
            	             ret = variable17; 
            	        }

            	    }
            	    break;
            	case 2:
            	    // Interp.g:137:7: int_literal
            	    {
            	        FOLLOWPUSH(FOLLOW_int_literal_in_var_or_int_literal424);
            	        int_literal18=int_literal(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulevar_or_int_literalEx;
            	        }

            	        {
            	            ret = int_literal18; 
            	        }

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulevar_or_int_literalEx; /* Prevent compiler warnings */
    rulevar_or_int_literalEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end var_or_int_literal */

/** 
 * $ANTLR start variable
 * Interp.g:140:1: variable returns [VariableElement * ret] : VARIABLE ;
 */
static VariableElement *
variable(pInterpParser ctx)
{   
    VariableElement * ret = NULL;

    pANTLR3_COMMON_TOKEN    VARIABLE19;

    /* Initialize rule variables
     */



      ret = new VariableElement();

    VARIABLE19       = NULL;

    {
        // Interp.g:144:3: ( VARIABLE )
        // Interp.g:144:5: VARIABLE
        {
            VARIABLE19 = (pANTLR3_COMMON_TOKEN) MATCHT(VARIABLE, &FOLLOW_VARIABLE_in_variable448); 
            if  (HASEXCEPTION())
            {
                goto rulevariableEx;
            }

            {
                 pANTLR3_STRING str = (VARIABLE19->getText(VARIABLE19));
                	       char * chars = (char *) str->chars;
                               ret->setText(std::string(chars)); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulevariableEx; /* Prevent compiler warnings */
    rulevariableEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end variable */

/** 
 * $ANTLR start int_literal
 * Interp.g:149:1: int_literal returns [IntegerElement * ret] : INT_LITERAL ;
 */
static IntegerElement *
int_literal(pInterpParser ctx)
{   
    IntegerElement * ret = NULL;

    pANTLR3_COMMON_TOKEN    INT_LITERAL20;

    /* Initialize rule variables
     */



      ret = new IntegerElement();

    INT_LITERAL20       = NULL;

    {
        // Interp.g:153:3: ( INT_LITERAL )
        // Interp.g:153:5: INT_LITERAL
        {
            INT_LITERAL20 = (pANTLR3_COMMON_TOKEN) MATCHT(INT_LITERAL, &FOLLOW_INT_LITERAL_in_int_literal478); 
            if  (HASEXCEPTION())
            {
                goto ruleint_literalEx;
            }

            {
                 pANTLR3_STRING str = (INT_LITERAL20->getText(INT_LITERAL20));
                	       char * chars = (char *) str->chars;
                               ret->setText(std::string(chars)); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleint_literalEx; /* Prevent compiler warnings */
    ruleint_literalEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end int_literal */

/** 
 * $ANTLR start addition
 * Interp.g:159:1: addition returns [AdditionOperationElement * ret] : el1= var_or_int_literal '+' el2= var_or_int_literal ;
 */
static AdditionOperationElement *
addition(pInterpParser ctx)
{   
    AdditionOperationElement * ret = NULL;

    Element * el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 Element *

    Element * el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 Element *

    /* Initialize rule variables
     */



      ret = new AdditionOperationElement();

    el1 = NULL;
    el2 = NULL;

    {
        // Interp.g:163:3: (el1= var_or_int_literal '+' el2= var_or_int_literal )
        // Interp.g:163:5: el1= var_or_int_literal '+' el2= var_or_int_literal
        {
            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_addition515);
            el1=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }

            {
                 ret->setLhs(el1); 
            }
             MATCHT(PLUS, &FOLLOW_PLUS_in_addition524); 
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_addition533);
            el2=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }

            {
                 ret->setRhs(el2); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleadditionEx; /* Prevent compiler warnings */
    ruleadditionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end addition */

/** 
 * $ANTLR start multiply
 * Interp.g:167:1: multiply returns [MultiplyOperationElement *ret] : el1= var_or_int_literal '*' el2= var_or_int_literal ;
 */
static MultiplyOperationElement *
multiply(pInterpParser ctx)
{   
    MultiplyOperationElement * ret = NULL;

    Element * el1;
    #undef	RETURN_TYPE_el1
    #define	RETURN_TYPE_el1 Element *

    Element * el2;
    #undef	RETURN_TYPE_el2
    #define	RETURN_TYPE_el2 Element *

    /* Initialize rule variables
     */



       ret=new MultiplyOperationElement();

    el1 = NULL;
    el2 = NULL;

    {
        // Interp.g:171:1: (el1= var_or_int_literal '*' el2= var_or_int_literal )
        // Interp.g:171:3: el1= var_or_int_literal '*' el2= var_or_int_literal
        {
            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_multiply555);
            el1=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultiplyEx;
            }

            {
                 ret->setLhs(el1); 
            }
             MATCHT(PRODUCT, &FOLLOW_PRODUCT_in_multiply564); 
            if  (HASEXCEPTION())
            {
                goto rulemultiplyEx;
            }

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_multiply571);
            el2=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultiplyEx;
            }

            {
                 ret->setRhs(el2); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulemultiplyEx; /* Prevent compiler warnings */
    rulemultiplyEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end multiply */

/** 
 * $ANTLR start print
 * Interp.g:175:1: print returns [PrintOperationElement * ret] : 'print' var_or_int_literal END_OF_STATEMENT ;
 */
static PrintOperationElement *
print(pInterpParser ctx)
{   
    PrintOperationElement * ret = NULL;

    Element * var_or_int_literal21;
    #undef	RETURN_TYPE_var_or_int_literal21
    #define	RETURN_TYPE_var_or_int_literal21 Element *

    /* Initialize rule variables
     */



      ret = new PrintOperationElement();

    var_or_int_literal21 = NULL;

    {
        // Interp.g:179:3: ( 'print' var_or_int_literal END_OF_STATEMENT )
        // Interp.g:179:5: 'print' var_or_int_literal END_OF_STATEMENT
        {
             MATCHT(15, &FOLLOW_15_in_print593); 
            if  (HASEXCEPTION())
            {
                goto ruleprintEx;
            }

            FOLLOWPUSH(FOLLOW_var_or_int_literal_in_print595);
            var_or_int_literal21=var_or_int_literal(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprintEx;
            }

            {
                ret->setChildElement(var_or_int_literal21); 
            }
             MATCHT(END_OF_STATEMENT, &FOLLOW_END_OF_STATEMENT_in_print603); 
            if  (HASEXCEPTION())
            {
                goto ruleprintEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleprintEx; /* Prevent compiler warnings */
    ruleprintEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ret;
}
/* $ANTLR end print */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
