/** \file
 *  This C source file was generated by $ANTLR version 3.1.3 Mar 18, 2009 10:09:25
 *
 *     -  From the grammar source file : Interp.g
 *     -                            On : 2009-10-12 22:49:40
 *     -                 for the lexer : InterpLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

#include <vector>
#include<iostream>
#include "Element.h"
#include "VariableElement.h"
#include "IntegerElement.h"
#include "MatrixValueElement.h"
#include "MatrixVariableElement.h"
#include "MatrixAssignmentOperationElement.h"
#include "MatrixPrintOperationElement.h"
#include "MatrixMultiplyOperationElement.h"
#include "MatrixAdditionOperationElement.h"
#include "AssignmentOperationElement.h"
#include "AdditionOperationElement.h"
#include "PrintOperationElement.h"
#include "MultiplyOperationElement.h"
#include "ParallelforOperationElement.h"

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "InterpLexer.h"
/* ----------------------------------------- */


/** String literals used by InterpLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x70, 0x61, 0x72, 0x61, 0x6C, 0x6C, 0x65, 0x6C, 0x66, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x70, 0x72, 0x69, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pInterpLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pInterpLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pInterpLexer_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or 16 bit input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_ASCII) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_ASCII

/* 8 bit "ASCII" (actually any 8 bit character set) */

#  define	    NEXTCHAR			((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP				((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR			((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP				((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define	    CONSUME()											\
{																	\
    if	(NEXTCHAR < (DATAP + INPUT->sizeBuf))						\
    {																\
		INPUT->charPositionInLine++;								\
		if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)		\
		{															\
			INPUT->line++;											\
			INPUT->charPositionInLine	= 0;						\
			INPUT->currentLine		= (void *)(NEXTCHAR + 1);		\
		}															\
		INPUT->nextChar = (void *)(NEXTCHAR + 1);					\
    }																\
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()				INPUT->istream->consume(INPUT->istream)
#define	    LA(n)					INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__15    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mT__16    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mEND_OF_STATEMENT    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mASSIGNMENT    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mPLUS    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mPRODUCT    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mRSQBRACKET    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mLSQBRACKET    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mVARIABLE    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mINT_LITERAL    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mWHITESPACE    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mMATRIXVARIABLE    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mMATRIXVALUE    (pInterpLexer ctx);
static ANTLR3_INLINE  void	mTokens    (pInterpLexer ctx);
static void	InterpLexerFree(pInterpLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
InterpLexerFree  (pInterpLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "Interp.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called InterpLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success pInterpLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pInterpLexer InterpLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return InterpLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called InterpLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success pInterpLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pInterpLexer InterpLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pInterpLexer ctx; // Context structure we will build and return

    ctx = (pInterpLexer) ANTLR3_CALLOC(1, sizeof(InterpLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in InterpLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our InterpLexer interface
     */
    ctx->mT__15	= mT__15;
    ctx->mT__16	= mT__16;
    ctx->mEND_OF_STATEMENT	= mEND_OF_STATEMENT;
    ctx->mASSIGNMENT	= mASSIGNMENT;
    ctx->mPLUS	= mPLUS;
    ctx->mPRODUCT	= mPRODUCT;
    ctx->mRSQBRACKET	= mRSQBRACKET;
    ctx->mLSQBRACKET	= mLSQBRACKET;
    ctx->mVARIABLE	= mVARIABLE;
    ctx->mINT_LITERAL	= mINT_LITERAL;
    ctx->mWHITESPACE	= mWHITESPACE;
    ctx->mMATRIXVARIABLE	= mMATRIXVARIABLE;
    ctx->mMATRIXVALUE	= mMATRIXVALUE;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= InterpLexerFree;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    ()* loopback of 208:14: ( ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' ) ':' )*
 */
static const ANTLR3_INT32 dfa5_eot[7] =
    {
	-1, -1, -1, -1, 6, -1, -1
    };
static const ANTLR3_INT32 dfa5_eof[7] =
    {
	-1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa5_min[7] =
    {
	123, 48, 44, 48, 58, -1, -1
    };
static const ANTLR3_INT32 dfa5_max[7] =
    {
	123, 57, 125, 57, 58, -1, -1
    };
static const ANTLR3_INT32 dfa5_accept[7] =
    {
	-1, -1, -1, -1, -1, 1, 2
    };
static const ANTLR3_INT32 dfa5_special[7] =
    {	
	-1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa5_T_empty	    NULL

static const ANTLR3_INT32 dfa5_T0[] =
    {
	1
    };static const ANTLR3_INT32 dfa5_T1[] =
    {
	5
    };static const ANTLR3_INT32 dfa5_T2[] =
    {
	3, -1, -1, -1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, 4
    };static const ANTLR3_INT32 dfa5_T3[] =
    {
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa5_transitions[] =
{
    dfa5_T0, dfa5_T3, dfa5_T2, dfa5_T3, dfa5_T1, dfa5_T_empty, dfa5_T_empty	
};


/* Declare tracking structure for Cyclic DFA 5
 */
static
ANTLR3_CYCLIC_DFA cdfa5
    =	{
	    5,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"()* loopback of 208:14: ( ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' ) ':' )*",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa5_eot,	    /* EOT table			    */
	    dfa5_eof,	    /* EOF table			    */
	    dfa5_min,	    /* Minimum tokens for each state    */
	    dfa5_max,	    /* Maximum tokens for each state    */
	    dfa5_accept,	/* Accept table			    */
	    dfa5_special,	/* Special transition states	    */
	    dfa5_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 5
 * ---------------------
 *//** Static dfa state tables for Cyclic dfa:
 *    ()* loopback of 208:19: ( INT_LITERAL ',' )*
 */
static const ANTLR3_INT32 dfa4_eot[4] =
    {
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa4_eof[4] =
    {
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa4_min[4] =
    {
	48, 44, -1, -1
    };
static const ANTLR3_INT32 dfa4_max[4] =
    {
	57, 125, -1, -1
    };
static const ANTLR3_INT32 dfa4_accept[4] =
    {
	-1, -1, 1, 2
    };
static const ANTLR3_INT32 dfa4_special[4] =
    {	
	-1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa4_T_empty	    NULL

static const ANTLR3_INT32 dfa4_T0[] =
    {
	2, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, 3
    };static const ANTLR3_INT32 dfa4_T1[] =
    {
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa4_transitions[] =
{
    dfa4_T1, dfa4_T0, dfa4_T_empty, dfa4_T_empty	
};


/* Declare tracking structure for Cyclic DFA 4
 */
static
ANTLR3_CYCLIC_DFA cdfa4
    =	{
	    4,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"()* loopback of 208:19: ( INT_LITERAL ',' )*",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa4_eot,	    /* EOT table			    */
	    dfa4_eof,	    /* EOF table			    */
	    dfa4_min,	    /* Minimum tokens for each state    */
	    dfa4_max,	    /* Maximum tokens for each state    */
	    dfa4_accept,	/* Accept table			    */
	    dfa4_special,	/* Special transition states	    */
	    dfa4_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 4
 * ---------------------
 *//** Static dfa state tables for Cyclic dfa:
 *    ()* loopback of 208:63: ( INT_LITERAL ',' )*
 */
static const ANTLR3_INT32 dfa6_eot[4] =
    {
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa6_eof[4] =
    {
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa6_min[4] =
    {
	48, 44, -1, -1
    };
static const ANTLR3_INT32 dfa6_max[4] =
    {
	57, 125, -1, -1
    };
static const ANTLR3_INT32 dfa6_accept[4] =
    {
	-1, -1, 1, 2
    };
static const ANTLR3_INT32 dfa6_special[4] =
    {	
	-1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa6_T_empty	    NULL

static const ANTLR3_INT32 dfa6_T0[] =
    {
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    };static const ANTLR3_INT32 dfa6_T1[] =
    {
	2, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, 3
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa6_transitions[] =
{
    dfa6_T0, dfa6_T1, dfa6_T_empty, dfa6_T_empty	
};


/* Declare tracking structure for Cyclic DFA 6
 */
static
ANTLR3_CYCLIC_DFA cdfa6
    =	{
	    6,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"()* loopback of 208:63: ( INT_LITERAL ',' )*",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa6_eot,	    /* EOT table			    */
	    dfa6_eof,	    /* EOF table			    */
	    dfa6_min,	    /* Minimum tokens for each state    */
	    dfa6_max,	    /* Maximum tokens for each state    */
	    dfa6_accept,	/* Accept table			    */
	    dfa6_special,	/* Special transition states	    */
	    dfa6_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 6
 * ---------------------
 *//** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__15 | T__16 | END_OF_STATEMENT | ASSIGNMENT | PLUS | PRODUCT | RSQBRACKET | LSQBRACKET | VARIABLE | INT_LITERAL | WHITESPACE | MATRIXVARIABLE | MATRIXVALUE );
 */
static const ANTLR3_INT32 dfa7_eot[30] =
    {
	-1, 14, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, 14, 14, -1, -1, 14, 14, 
	14, 14, 14, 23, 14, -1, 14, 14, 14, 14, 29, -1
    };
static const ANTLR3_INT32 dfa7_eof[30] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa7_min[30] =
    {
	9, 65, -1, -1, -1, -1, -1, -1, 65, -1, -1, -1, 65, 65, -1, -1, 65, 65, 
	65, 65, 65, 65, 65, -1, 65, 65, 65, 65, 65, -1
    };
static const ANTLR3_INT32 dfa7_max[30] =
    {
	123, 122, -1, -1, -1, -1, -1, -1, 122, -1, -1, -1, 122, 122, -1, -1, 122, 
	122, 122, 122, 122, 122, 122, -1, 122, 122, 122, 122, 122, -1
    };
static const ANTLR3_INT32 dfa7_accept[30] =
    {
	-1, -1, 3, 4, 5, 6, 7, 8, -1, 10, 11, 13, -1, -1, 9, 12, -1, -1, -1, -1, 
	-1, -1, -1, 2, -1, -1, -1, -1, -1, 1
    };
static const ANTLR3_INT32 dfa7_special[30] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa7_T_empty	    NULL

static const ANTLR3_INT32 dfa7_T0[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 8, 8, 8, 21, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T1[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 19, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T2[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 17, 8, 8, 8, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T3[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 8, 28, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T4[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 26, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T5[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	27, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T6[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 24, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T7[] =
    {
	10, 10, -1, -1, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5, 4, -1, -1, 
	-1, -1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, -1, 2, -1, 3, -1, -1, -1, 8, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 
	-1, 6, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 11
    };static const ANTLR3_INT32 dfa7_T8[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 25, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T9[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 20, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T10[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 22, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T11[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 8, 16, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T12[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 18, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T13[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa7_T14[] =
    {
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 15, -1, -1, -1, -1, -1, 12, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
	8, 8, 8, 13, 8, 8, 8, 8, 8, 8, 8, 8
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa7_transitions[] =
{
    dfa7_T7, dfa7_T14, dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, 
    dfa7_T_empty, dfa7_T_empty, dfa7_T13, dfa7_T_empty, dfa7_T_empty, dfa7_T_empty, 
    dfa7_T11, dfa7_T2, dfa7_T_empty, dfa7_T_empty, dfa7_T12, dfa7_T1, dfa7_T9, 
    dfa7_T0, dfa7_T10, dfa7_T13, dfa7_T6, dfa7_T_empty, dfa7_T8, dfa7_T4, 
    dfa7_T5, dfa7_T3, dfa7_T13, dfa7_T_empty	
};


/* Declare tracking structure for Cyclic DFA 7
 */
static
ANTLR3_CYCLIC_DFA cdfa7
    =	{
	    7,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__15 | T__16 | END_OF_STATEMENT | ASSIGNMENT | PLUS | PRODUCT | RSQBRACKET | LSQBRACKET | VARIABLE | INT_LITERAL | WHITESPACE | MATRIXVARIABLE | MATRIXVALUE );",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa7_eot,	    /* EOT table			    */
	    dfa7_eof,	    /* EOF table			    */
	    dfa7_min,	    /* Minimum tokens for each state    */
	    dfa7_max,	    /* Maximum tokens for each state    */
	    dfa7_accept,	/* Accept table			    */
	    dfa7_special,	/* Special transition states	    */
	    dfa7_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 7
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */ 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 26:7: ( 'parallelfor' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__15
 *
 * Looks to match the characters the constitute the token T__15
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__15(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__15;
       
    
    // Interp.g:26:7: ( 'parallelfor' )
    // Interp.g:26:9: 'parallelfor'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleT__15Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__15Ex; /* Prevent compiler warnings */
    ruleT__15Ex: ;

}
// $ANTLR end T__15

//   Comes from: 27:7: ( 'print' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__16
 *
 * Looks to match the characters the constitute the token T__16
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__16(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__16;
       
    
    // Interp.g:27:7: ( 'print' )
    // Interp.g:27:9: 'print'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleT__16Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__16Ex; /* Prevent compiler warnings */
    ruleT__16Ex: ;

}
// $ANTLR end T__16

//   Comes from: 198:17: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start END_OF_STATEMENT
 *
 * Looks to match the characters the constitute the token END_OF_STATEMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEND_OF_STATEMENT(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = END_OF_STATEMENT;
       
    
    // Interp.g:198:17: ( ';' )
    // Interp.g:198:19: ';'
    {
        MATCHC(';'); 
        if  (HASEXCEPTION())
        {
            goto ruleEND_OF_STATEMENTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleEND_OF_STATEMENTEx; /* Prevent compiler warnings */
    ruleEND_OF_STATEMENTEx: ;

}
// $ANTLR end END_OF_STATEMENT

//   Comes from: 199:11: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ASSIGNMENT
 *
 * Looks to match the characters the constitute the token ASSIGNMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mASSIGNMENT(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ASSIGNMENT;
       
    
    // Interp.g:199:11: ( '=' )
    // Interp.g:199:13: '='
    {
        MATCHC('='); 
        if  (HASEXCEPTION())
        {
            goto ruleASSIGNMENTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleASSIGNMENTEx; /* Prevent compiler warnings */
    ruleASSIGNMENTEx: ;

}
// $ANTLR end ASSIGNMENT

//   Comes from: 200:5: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPLUS(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PLUS;
       
    
    // Interp.g:200:5: ( '+' )
    // Interp.g:200:7: '+'
    {
        MATCHC('+'); 
        if  (HASEXCEPTION())
        {
            goto rulePLUSEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 201:8: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PRODUCT
 *
 * Looks to match the characters the constitute the token PRODUCT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPRODUCT(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PRODUCT;
       
    
    // Interp.g:201:8: ( '*' )
    // Interp.g:201:10: '*'
    {
        MATCHC('*'); 
        if  (HASEXCEPTION())
        {
            goto rulePRODUCTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto rulePRODUCTEx; /* Prevent compiler warnings */
    rulePRODUCTEx: ;

}
// $ANTLR end PRODUCT

//   Comes from: 202:11: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RSQBRACKET
 *
 * Looks to match the characters the constitute the token RSQBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRSQBRACKET(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RSQBRACKET;
       
    
    // Interp.g:202:11: ( ']' )
    // Interp.g:202:13: ']'
    {
        MATCHC(']'); 
        if  (HASEXCEPTION())
        {
            goto ruleRSQBRACKETEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleRSQBRACKETEx; /* Prevent compiler warnings */
    ruleRSQBRACKETEx: ;

}
// $ANTLR end RSQBRACKET

//   Comes from: 203:11: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LSQBRACKET
 *
 * Looks to match the characters the constitute the token LSQBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLSQBRACKET(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LSQBRACKET;
       
    
    // Interp.g:203:11: ( '[' )
    // Interp.g:203:13: '['
    {
        MATCHC('['); 
        if  (HASEXCEPTION())
        {
            goto ruleLSQBRACKETEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLSQBRACKETEx; /* Prevent compiler warnings */
    ruleLSQBRACKETEx: ;

}
// $ANTLR end LSQBRACKET

//   Comes from: 204:9: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start VARIABLE
 *
 * Looks to match the characters the constitute the token VARIABLE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mVARIABLE(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = VARIABLE;
       
    
    // Interp.g:204:9: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
    // Interp.g:204:11: ( 'a' .. 'z' | 'A' .. 'Z' )+
    {
        // Interp.g:204:11: ( 'a' .. 'z' | 'A' .. 'Z' )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA1_0 = LA(1);
        	    if ( (((LA1_0 >= 'A') && (LA1_0 <= 'Z')) || ((LA1_0 >= 'a') && (LA1_0 <= 'z'))) ) 
        	    {
        	        alt1=1;
        	    }

        	}
        	switch (alt1) 
        	{
        	    case 1:
        	        // Interp.g:
        	        {
        	            if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleVARIABLEEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleVARIABLEEx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleVARIABLEEx; /* Prevent compiler warnings */
    ruleVARIABLEEx: ;

}
// $ANTLR end VARIABLE

//   Comes from: 205:12: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT_LITERAL
 *
 * Looks to match the characters the constitute the token INT_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT_LITERAL(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT_LITERAL;
       
    
    // Interp.g:205:12: ( ( '0' .. '9' )+ )
    // Interp.g:205:14: ( '0' .. '9' )+
    {
        // Interp.g:205:14: ( '0' .. '9' )+
        {
            int cnt2=0;

            for (;;)
            {
                int alt2=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA2_0 = LA(1);
        	    if ( (((LA2_0 >= '0') && (LA2_0 <= '9'))) ) 
        	    {
        	        alt2=1;
        	    }

        	}
        	switch (alt2) 
        	{
        	    case 1:
        	        // Interp.g:205:15: '0' .. '9'
        	        {
        	            MATCHRANGE('0', '9'); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleINT_LITERALEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt2 >= 1 )
        		{
        		    goto loop2;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINT_LITERALEx;
        	}
        	cnt2++;
            }
            loop2: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleINT_LITERALEx; /* Prevent compiler warnings */
    ruleINT_LITERALEx: ;

}
// $ANTLR end INT_LITERAL

//   Comes from: 206:12: ( ( ' ' | '\\t' | '\\n' | '\\r' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WHITESPACE
 *
 * Looks to match the characters the constitute the token WHITESPACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWHITESPACE(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WHITESPACE;
       
    
    // Interp.g:206:12: ( ( ' ' | '\\t' | '\\n' | '\\r' )+ )
    // Interp.g:206:14: ( ' ' | '\\t' | '\\n' | '\\r' )+
    {
        // Interp.g:206:14: ( ' ' | '\\t' | '\\n' | '\\r' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA3_0 = LA(1);
        	    if ( (((LA3_0 >= '\t') && (LA3_0 <= '\n')) || LA3_0 == '\r' || LA3_0 == ' ') ) 
        	    {
        	        alt3=1;
        	    }

        	}
        	switch (alt3) 
        	{
        	    case 1:
        	        // Interp.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleWHITESPACEEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWHITESPACEEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }
        {
            LEXSTATE->channel = HIDDEN; 
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWHITESPACEEx; /* Prevent compiler warnings */
    ruleWHITESPACEEx: ;

}
// $ANTLR end WHITESPACE

//   Comes from: 207:15: ( VARIABLE LSQBRACKET RSQBRACKET )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MATRIXVARIABLE
 *
 * Looks to match the characters the constitute the token MATRIXVARIABLE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMATRIXVARIABLE(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MATRIXVARIABLE;
       
    
    // Interp.g:207:15: ( VARIABLE LSQBRACKET RSQBRACKET )
    // Interp.g:207:16: VARIABLE LSQBRACKET RSQBRACKET
    {
        /* 207:16: VARIABLE LSQBRACKET RSQBRACKET */
        mVARIABLE(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleMATRIXVARIABLEEx;
        }

        /* 207:16: VARIABLE LSQBRACKET RSQBRACKET */
        mLSQBRACKET(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleMATRIXVARIABLEEx;
        }

        /* 207:16: VARIABLE LSQBRACKET RSQBRACKET */
        mRSQBRACKET(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleMATRIXVARIABLEEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleMATRIXVARIABLEEx; /* Prevent compiler warnings */
    ruleMATRIXVARIABLEEx: ;

}
// $ANTLR end MATRIXVARIABLE

//   Comes from: 208:12: ( ( ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' ) ':' )* ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MATRIXVALUE
 *
 * Looks to match the characters the constitute the token MATRIXVALUE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMATRIXVALUE(pInterpLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MATRIXVALUE;
       
    
    // Interp.g:208:12: ( ( ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' ) ':' )* ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' ) )
    // Interp.g:208:14: ( ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' ) ':' )* ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' )
    {

        // Interp.g:208:14: ( ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' ) ':' )*

        for (;;)
        {
            int alt5=2;
            alt5 = cdfa5.predict(ctx, RECOGNIZER, ISTREAM, &cdfa5);
            if  (HASEXCEPTION())
            {
                goto ruleMATRIXVALUEEx;
            }

            switch (alt5) 
            {
        	case 1:
        	    // Interp.g:208:15: ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' ) ':'
        	    {
        	        // Interp.g:208:15: ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' )
        	        // Interp.g:208:16: '{' ( INT_LITERAL ',' )* INT_LITERAL '}'
        	        {
        	            MATCHC('{'); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleMATRIXVALUEEx;
        	            }


        	            // Interp.g:208:19: ( INT_LITERAL ',' )*

        	            for (;;)
        	            {
        	                int alt4=2;
        	                alt4 = cdfa4.predict(ctx, RECOGNIZER, ISTREAM, &cdfa4);
        	                if  (HASEXCEPTION())
        	                {
        	                    goto ruleMATRIXVALUEEx;
        	                }

        	                switch (alt4) 
        	                {
        	            	case 1:
        	            	    // Interp.g:208:20: INT_LITERAL ','
        	            	    {
        	            	        /* 208:20: INT_LITERAL ',' */
        	            	        mINT_LITERAL(ctx ); 
        	            	        if  (HASEXCEPTION())
        	            	        {
        	            	            goto ruleMATRIXVALUEEx;
        	            	        }

        	            	        MATCHC(','); 
        	            	        if  (HASEXCEPTION())
        	            	        {
        	            	            goto ruleMATRIXVALUEEx;
        	            	        }


        	            	    }
        	            	    break;

        	            	default:
        	            	    goto loop4;	/* break out of the loop */
        	            	    break;
        	                }
        	            }
        	            loop4: ; /* Jump out to here if this rule does not match */

        	            /* 208:16: '{' ( INT_LITERAL ',' )* INT_LITERAL '}' */
        	            mINT_LITERAL(ctx ); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleMATRIXVALUEEx;
        	            }

        	            MATCHC('}'); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleMATRIXVALUEEx;
        	            }


        	        }

        	        MATCHC(':'); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleMATRIXVALUEEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop5;	/* break out of the loop */
        	    break;
            }
        }
        loop5: ; /* Jump out to here if this rule does not match */

        // Interp.g:208:59: ( '{' ( INT_LITERAL ',' )* INT_LITERAL '}' )
        // Interp.g:208:60: '{' ( INT_LITERAL ',' )* INT_LITERAL '}'
        {
            MATCHC('{'); 
            if  (HASEXCEPTION())
            {
                goto ruleMATRIXVALUEEx;
            }


            // Interp.g:208:63: ( INT_LITERAL ',' )*

            for (;;)
            {
                int alt6=2;
                alt6 = cdfa6.predict(ctx, RECOGNIZER, ISTREAM, &cdfa6);
                if  (HASEXCEPTION())
                {
                    goto ruleMATRIXVALUEEx;
                }

                switch (alt6) 
                {
            	case 1:
            	    // Interp.g:208:64: INT_LITERAL ','
            	    {
            	        /* 208:64: INT_LITERAL ',' */
            	        mINT_LITERAL(ctx ); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleMATRIXVALUEEx;
            	        }

            	        MATCHC(','); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleMATRIXVALUEEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */

            /* 208:60: '{' ( INT_LITERAL ',' )* INT_LITERAL '}' */
            mINT_LITERAL(ctx ); 
            if  (HASEXCEPTION())
            {
                goto ruleMATRIXVALUEEx;
            }

            MATCHC('}'); 
            if  (HASEXCEPTION())
            {
                goto ruleMATRIXVALUEEx;
            }


        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleMATRIXVALUEEx; /* Prevent compiler warnings */
    ruleMATRIXVALUEEx: ;

}
// $ANTLR end MATRIXVALUE

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(pInterpLexer ctx)
{
    {
        //  Interp.g:1:8: ( T__15 | T__16 | END_OF_STATEMENT | ASSIGNMENT | PLUS | PRODUCT | RSQBRACKET | LSQBRACKET | VARIABLE | INT_LITERAL | WHITESPACE | MATRIXVARIABLE | MATRIXVALUE )
        
        ANTLR3_UINT32 alt7;

        alt7=13;

        alt7 = cdfa7.predict(ctx, RECOGNIZER, ISTREAM, &cdfa7);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt7) 
        {
    	case 1:
    	    // Interp.g:1:10: T__15
    	    {
    	        /* 1:10: T__15 */
    	        mT__15(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // Interp.g:1:16: T__16
    	    {
    	        /* 1:16: T__16 */
    	        mT__16(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // Interp.g:1:22: END_OF_STATEMENT
    	    {
    	        /* 1:22: END_OF_STATEMENT */
    	        mEND_OF_STATEMENT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // Interp.g:1:39: ASSIGNMENT
    	    {
    	        /* 1:39: ASSIGNMENT */
    	        mASSIGNMENT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // Interp.g:1:50: PLUS
    	    {
    	        /* 1:50: PLUS */
    	        mPLUS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // Interp.g:1:55: PRODUCT
    	    {
    	        /* 1:55: PRODUCT */
    	        mPRODUCT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // Interp.g:1:63: RSQBRACKET
    	    {
    	        /* 1:63: RSQBRACKET */
    	        mRSQBRACKET(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // Interp.g:1:74: LSQBRACKET
    	    {
    	        /* 1:74: LSQBRACKET */
    	        mLSQBRACKET(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // Interp.g:1:85: VARIABLE
    	    {
    	        /* 1:85: VARIABLE */
    	        mVARIABLE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // Interp.g:1:94: INT_LITERAL
    	    {
    	        /* 1:94: INT_LITERAL */
    	        mINT_LITERAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // Interp.g:1:106: WHITESPACE
    	    {
    	        /* 1:106: WHITESPACE */
    	        mWHITESPACE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // Interp.g:1:117: MATRIXVARIABLE
    	    {
    	        /* 1:117: MATRIXVARIABLE */
    	        mMATRIXVARIABLE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // Interp.g:1:132: MATRIXVALUE
    	    {
    	        /* 1:132: MATRIXVALUE */
    	        mMATRIXVALUE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
